ssvlabs/ssv

ibft/change_round_test.go, ibft/ibft_test.go, ibft/instance_test.go, ibft/pre_prepare_test.go, ibft/prepare_test.go
Hi guys,
Draft PR for discussion :) changes applied only for Unit Tests as suggestions
- Refactoring namings for better and fluent readability
- Fixing minor typos found
@begmaroman @alonmuroch please, let me know your thoughts
=> ssv - ibft - tests - suggestion for namings and fixing typos

ibft/IBFT.md, ibft/README.md
Documentation - IBFT - Part I
- IBFT Background and references
TODOs: diagram for states and consensus flow - by BLOX Design
@alonmuroch , please take a look.
=> ssv - ibft - Readme - IBFT explained Part 1

ibft/change_round.go, ibft/commit.go, ibft/ibft.go, ibft/instance.go, ibft/leader.go, ibft/msg_auth.go, ibft/msgqueue/message_queue.go, ibft/pipeline.go, ibft/pre_prepare.go, ibft/prepare.go, ibft/proto/msgs.go, ibft/proto/params.go, ibft/proto/params_test.go, ibft/proto/state.go
Adjusting comments to exported functions according to **lint.sh**
@roman-blox  @lior-blox @alonmuroch, please review.
=> ssv - Lint - exported functions - adding comments to functions

ibft/pipeline/auth/msg_auth.go, ibft/pipeline/changeround/add_message.go, ibft/pipeline/changeround/validate.go
Fix to ibft - pipelines - files which were recently refactored
- function reference fix
@roman-blox  @lior-blox please review
=> ssv - ibft - pipelines - fix to function reference

ibft/IBFT.md
=> ibft - readme - adjusting Attestation and Proposal references

.gitlab-ci.yml, cli/ssvnode/node.go, eth1/client.go, eth1/goeth/goETH.go, eth1/goeth/goETH_test.go, node/node.go, node/node_eth1.go, node/node_eth1_test.go, node/storage.go, node/storage_test.go, validator/controller.go, validator/validator.go
This PR adds the ability for an SSV node to sync all the contract events from the past.
=> Add Sync of ETH1 Events

cli/ssvnode/node.go, config/config.yaml, docs/OPERATOR_GETTING_STARTED.md, eth1/goeth/goETH.go, validator/storage/storage.go
This PR updates operator-key config entry name
=> OperatorKey config is not aligned

ibft/ibft.go, validator/duty_execution.go, validator/test_utils.go
Handle ibft instance errors upstream instead of just log
=> ibft instance error handeling

ibft/event_loop.go, network/p2p/p2p_sync.go, network/p2p/p2p_sync_test.go, utils/logex/zap.go, utils/tasks/exec_timeout.go, utils/tasks/exec_timeout_test.go
Resolve https://github.com/bloxapp/ssv/issues/157
=> Central logger

Dockerfile, Makefile, cli/cli.go, cli/version.go, docs/DEV_GUIDE.md
Resolve https://github.com/bloxapp/ssv/issues/164
=> Add version during build and expose a CLI

ibft/change_round.go, ibft/event_loop.go, ibft/event_loop_test.go, ibft/instance.go, ibft/instance_test.go, ibft/partial_change_round.go, ibft/roundtimer/timer.go, ibft/roundtimer/timer_test.go
this PR refactors the iBFT round timer to both something more robust and also to eliminate the go routine issues we had
=> new round timer struct refactoring

exporter/query_handlers.go, exporter/readers.go
Resolve https://github.com/bloxapp/ssv/issues/181
=> Sort exporter results by index

ibft/ibft_network.go
Resolve https://github.com/bloxapp/ssv/issues/193
=> Align wait interval limit

eth1/goeth/goETH.go
Resolve https://github.com/bloxapp/ssv/issues/195
=> Handle eth1 disconnection

cli/bootnode/boot_node.go, cli/config/config.go, cli/exporter/node.go, cli/generate_operator_keys.go, cli/operator/node.go, docs/OPERATOR_GETTING_STARTED.md, ibft/ibft_sync_test.go, ibft/simulation/main.go, network/p2p/p2p_sync_test.go, utils/logex/zap.go, utils/tasks/exec_timeout_test.go
Resolve https://github.com/bloxapp/ssv/issues/198
=> JSON format for logs

beacon/beacon.go, beacon/goclient/committee.go, operator/node.go, validator/test_utils.go
when fetching duties from BN, for all the duties we send subscribe committee to subnet
=> subscribe to subnet

network/msgqueue/message_queue.go, network/msgqueue/message_queue_test.go
* use `RWMutex` to allow read locks
* use `patrickmn/go-cache` to store data
=> Fix Concurrency Issues in MessageQueue

cli/exporter/node.go, cli/operator/node.go, eth1/client.go, eth1/goeth/goETH.go
Resolve https://github.com/bloxapp/ssv/issues/220
=> Eth1 Dial Timeout

cli/bootnode/boot_node.go, cli/config/config.go, cli/exporter/node.go, cli/generate_operator_keys.go, cli/operator/node.go, docs/OPERATOR_GETTING_STARTED.md, ibft/ibft_sync_test.go, ibft/simulation/main.go, network/p2p/p2p_sync_test.go, utils/logex/zap.go, utils/tasks/exec_timeout_test.go
Resolve https://github.com/bloxapp/ssv/issues/206
=> Log levels format

.k8/yamls/ssv-exporter.yml, .k8/yamls/ssv-node-v2-1-deployment.yml, .k8/yamls/ssv-node-v2-2-deployment.yml, .k8/yamls/ssv-node-v2-3-deployment.yml, .k8/yamls/ssv-node-v2-4-deployment.yml, cli/operator/node.go
Complements https://github.com/bloxapp/ssv/pull/223/commits/6e2ffc8c4bc0744b5d43a6ea79f06d7221115699
=> Enable profiling on k8s nodes

.gitlab-ci.yml, beacon/goclient/attest.go, beacon/goclient/singing.go, ibft/ibft_running_instance.go
Resolve https://github.com/bloxapp/ssv/issues/233
Resolve https://github.com/bloxapp/ssv/issues/235
=> Handle panic errors

ibft/sync/history.go, validator/controller.go
Resolve https://github.com/bloxapp/ssv/issues/241
=> Validator Sync

ibft/sync/history.go, validator/controller.go
Resolve https://github.com/bloxapp/ssv/issues/241
=> History sync fix

operator/duties/controller.go, operator/duties/fetcher.go, validator/controller.go
This PR contains improvements to logs in case there are no validators
=> Log improvements

ibft/change_round.go, ibft/event_loop.go, ibft/ibft_running_instance.go, ibft/sync/speedup/speedup.go
* Fix error in pre-prepare message pipeline
* Resolve https://github.com/bloxapp/ssv/issues/260 
* Improve logs - use correct level for debug logs that were written with error level
=> Merge v0.0.15

network/p2p/p2p.go
Avoid printing all connected peers, by adding a filtering of "invisible peers" (e.g. exporter)
=> Print correct connected peers

docs/DEV_GUIDE.md, monitoring/README.md, monitoring/grafana/dashboard_ssv_operator.json, monitoring/prometheus/prometheus.yaml
Adding `SSV Operator` dashboard and docs on how to setup in Grafana.
The following diagram describes the overall setup of monitoring + explorer on SSV network:
=> Grafana Dashborad

beacon/goclient/attest.go, beacon/goclient/singing.go, validator/signature.go, validator/signature_test.go
Resolve https://github.com/bloxapp/ssv/issues/235
=> Fix panic on empty root

exporter/node.go, utils/tasks/dispatcher.go, utils/tasks/dispatcher_test.go
Make dispatcher task-distinct for avoiding several tasks for the same validator
=> Improve dispatcher

.gitlab-ci.yml, eth1/goeth/goETH.go
Resolve https://github.com/bloxapp/ssv/issues/299
=> Fix ETH1 sync 

.gitlab-ci.yml, eth1/sync.go, eth1/sync_test.go, exporter/node.go, exporter/registry_handlers.go, operator/node.go, pubsub/observer.go, utils/tasks/dispatcher.go, utils/tasks/simple_queue.go, utils/tasks/simple_queue_test.go, validator/controller.go
Resolve https://github.com/bloxapp/ssv/issues/296
Resolve https://github.com/bloxapp/ssv/issues/297
=> Change indices fetching to work synchronously

.gitlab-ci.yml, storage/kv/badger.go, validator/controller.go, validator/validator.go, validator/validators_map.go
Avoid starting validators without index, and start once the index is fetched (if it was missing).
This helps to get a clear understanding about validator status.
In addition, Resolve https://github.com/bloxapp/ssv/issues/315
=> Refactor start validator flow

storage/kv/badger.go, storage/kv/badger_test.go
Resolve https://github.com/bloxapp/ssv/issues/318
Tested DB size (items):
=> Fix get all collection by separating key from value fetching

network/p2p/p2p.go
Fixing `fatal error: concurrent map read and map write`
=> Add lock for safe access to topics map

.gitlab-ci.yml, .k8/yamls/ssv-exporter.yml, .k8/yamls/ssv-node-v2-1-deployment.yml, .k8/yamls/ssv-node-v2-2-deployment.yml, .k8/yamls/ssv-node-v2-3-deployment.yml, .k8/yamls/ssv-node-v2-4-deployment.yml, cli/exporter/node.go, cli/operator/node.go, storage/basedb/storage.go, storage/kv/badger.go, storage/kv/badger_test.go, storage/kv/metrics.go
Added reporting for DB metrics, to help understand https://github.com/bloxapp/ssv/issues/318
Notes:
* Currently protected with a flag/config
* operator dashboard should be updated as well
=> DB Reporting

.k8/yamls/ssv-exporter.yml, .k8/yamls/ssv-node-v2-1-deployment.yml, .k8/yamls/ssv-node-v2-2-deployment.yml, .k8/yamls/ssv-node-v2-3-deployment.yml, .k8/yamls/ssv-node-v2-4-deployment.yml
Resolve https://github.com/bloxapp/ssv/issues/318
=> Turn off pubsub tracing

eth1/goeth/goETH.go, network/p2p/metrics.go
Resolve https://github.com/bloxapp/ssv/issues/299
Added a dynamic batch size to overcome series of blocks that contains lots of events
=> Dynamic batch size for ETH1 sync

.gitlab-ci.yml, exporter/ibft/commit_reader.go, exporter/ibft/decided_reader.go, exporter/node.go, exporter/query_handlers_test.go, ibft/proto/msgs.go, utils/tasks/exec_queue_test.go
Added commit reader to handle late commit messages
TODO: add tests in next version
=> Exporter - added commit reader

network/p2p/metrics.go, network/p2p/p2p.go, network/p2p/peers_index.go, network/p2p/peers_index_test.go
Resolve https://github.com/bloxapp/ssv/issues/349:
* added ID Service (libp2p identity)
* added a new component (`PeersIndex`) to index data of peers such as `UserAgent`
Resolve https://github.com/bloxapp/ssv/issues/289, https://github.com/bloxapp/ssv/issues/348
* change log level to `debug` in case failed
=> Fix UA and host self check

network/p2p/addr_utils.go, network/p2p/addr_utils_test.go, network/p2p/config.go, network/p2p/discovery.go, network/p2p/discovery_discv5.go, network/p2p/discovery_mdns.go, network/p2p/discovery_test.go, network/p2p/options.go, network/p2p/p2p.go, network/p2p/p2p_pubsub.go, network/p2p/p2p_stream.go, network/p2p/p2p_sync_test.go, network/p2p/p2p_test.go, network/p2p/utils.go
- Resolve https://github.com/bloxapp/ssv/issues/390
=> Refactor network package

Makefile
SSV uses UDP port 12000, not TCP port
=> Fix docker port publishing

eth1/events.go, network/p2p/config.go, network/p2p/discovery.go, network/p2p/discovery_discv5.go, network/p2p/p2p.go, network/p2p/p2p_pubsub.go
Added flag to turn on/off network logs
=> Flag for network trace

exporter/api/outbound_msg_q.go, exporter/api/server.go, exporter/api/server_test.go
Resolve https://github.com/bloxapp/ssv/issues/411
=> Exporter Stream - close connections if socket does not responds

exporter/ibft/decided_reader.go, exporter/ibft/factory.go, exporter/node.go, exporter/node_test.go, exporter/registry_handlers.go, exporter/storage/validators.go, exporter/storage/validators_test.go, exporter/validators_metadata.go, validator/controller.go, validator/storage/share.go, validator/storage/storage.go, validator/utils.go
Resolve https://github.com/bloxapp/ssv/issues/389
=> Exporter - fix update validator metadata

network/p2p/listeners.go, network/p2p/listeners_test.go, network/p2p/p2p.go, network/p2p/p2p_stream.go
- use RWMutex for listeners lock
- add randomness to listener ID
=> Fix internal listeners

.gitignore, .gitlab-ci.yml, cli/exporter/node.go, cli/operator/node.go, config/config.example.yaml, config/config.yaml, ibft/sync/history/fetch_highest.go, ibft/sync/speedup/speedup.go, network/p2p/config.go, network/p2p/discovery_discv5.go, network/p2p/listeners.go, network/p2p/metrics.go, network/p2p/p2p.go, network/p2p/p2p_pubsub.go, network/p2p/p2p_test.go, operator/storage_test.go
Adding node type (Unknown, operator, exporter) to user agent (temp solution until network refactoring)
* report to Operator table in grafana under "type" header
* once fetching peers for topic it will filter all exporter node's type
=> Node Type (User agent)

exporter/ibft/decided_reader.go, ibft/controller/controller.go, ibft/controller/controller_decided.go, ibft/controller/controller_sync.go, ibft/controller/metrics.go, network/commons/peers.go, network/p2p/p2p.go, network/p2p/peers_index.go, validator/duty_execution.go, validator/metrics.go, validator/validator.go
Mitigate https://github.com/bloxapp/ssv/issues/436: 
- using `Retry` for IBFT sync, as sync usually fails at start when not all peers are discovered
- peer indexing and node type alignment (to ask sync from relevant nodes)
Resolve https://github.com/bloxapp/ssv/issues/437 (Grafana: fix iBFT status)
=> Fix IBFT controller init

cli/exporter/node.go, cli/operator/node.go, operator/storage.go, utils/boot_node/node.go
p2p private key logs confuse users. 
Need to change to logs to be more clear.
=> private key logs improves

cli/exporter/node.go, cli/operator/node.go, network/p2p/p2p.go, network/p2p/storage.go, network/p2p/storage_test.go, network/p2p/sync_stream_test.go, network/p2p/utils.go, utils/boot_node/node.go, utils/keys.go
=> Stage to main (v0.1.5 preparation)

docs/OPERATOR_GETTING_STARTED.md
Resolve https://github.com/bloxapp/ssv/issues/454
=> Limit and rotate logs in 'getting started' guide

ibft/controller/controller_running_instance.go, ibft/instance/instance.go
Resolve https://github.com/bloxapp/ssv/issues/451
Resolve #452 
**NOTE:** `i.currentInstance` access is not thread-safe but this is general issue we need to solve and is not covered by this PR
=> Fix panic on instance state

Dockerfile
- added build parameter for specifying a custom app version instead of relying on git tag
e.g. `docker build -t ssv-node --build-arg APP_VERSION="v0.1.7-custom" .`
=> AppVersion build parameter for docker

cli/exporter/node.go, cli/operator/node.go
Resolve https://github.com/bloxapp/ssv/issues/460
=> Start monitoring before ETH1 sync

config/config.yaml, dev.Dockerfile
Add AIR tag to dev.docker in order to avoid issue accruing in master branch
=> Air v1.27.8

ibft/controller/controller.go, ibft/controller/controller_sync.go, ibft/controller/controller_sync_test.go, ibft/simulation/main.go, validator/controller.go, validator/validator.go
- added `HistorySyncBackOff` flag to control the work load coming from sync requests
=> Sync Backoff

.gitlab-ci.yml, ibft/pipeline/auth/msg_lambda.go
Log used to add trace which caused cpu consuming .
=> Auth Pipeline Log

docs/specs/NETWORKING.md, docs/specs/README.md
- Added specs directory and README
- Added a placeholder for networking spec
=> Specs directory

exporter/api/conn.go, exporter/ibft/decided_reader.go, exporter/validators_metadata.go
- added a lock to handle new decided messages (resolve https://github.com/bloxapp/ssv/issues/513)
- added state management to decided reader (resolve https://github.com/bloxapp/ssv/issues/514)
- removed some redundant logs
=> Exporter: decided messages stream

cli/operator/node.go, operator/storage.go, operator/storage_test.go, utils/migrationutils/migrator_test.go, utils/rsaencryption/rsa_encryption.go
Add flag (default false) to whether generate operator private key if there is no exist one or passed from config.
If flag is false and no key exist or passed, panic will raise
=> add operator pk auto generate flag

cli/exporter/node.go, exporter/api/broadcaster_test.go, exporter/api/conn.go, exporter/api/server.go, exporter/api/server_test.go, exporter/node_test.go
- Added flag for enabling websocket ping
- Fixed/aligned connection struct
=> Exporter: websocket ping flag

ibft/controller/controller_running_instance.go, ibft/instance/event_loop.go, ibft/instance/event_loop_test.go, ibft/instance/instance.go, ibft/instance/instance_test.go, ibft/instance/roundtimer/timer.go, ibft/instance/roundtimer/timer_test.go
Resolve #528 
- added state (uint32) + atomic to avoid locks
- added context to kill gracefully
- added test
=> Refactor Round Timer

ibft/instance/roundtimer/timer.go
otherwise 'running' could lead to ambiguity
=> round timer - adding reset state

ibft/instance/event_loop.go, ibft/instance/eventqueue/queue.go, network/p2p/p2p_decided.go, network/p2p/p2p_ibft.go, validator/validator.go
Add more details for broadcast logs in order to ease the issues investigation
=> Broadcast logs

config/example_share.yaml
Closes #541 
As per issue description
=> config: add `OwnerAddress` field to `example_share.yaml`

.gitlab-ci.yml, ibft/controller/controller_sync.go
Fixes https://github.com/bloxapp/ssv/issues/538
=> ibft/controller: fix panic in `ProcessSyncMessage`

ibft/controller/controller.go, ibft/controller/controller_decided.go, ibft/controller/controller_decided_test.go, ibft/controller/controller_network.go, ibft/controller/controller_running_instance.go, ibft/controller/controller_sequence.go, ibft/controller/controller_sequence_test.go, ibft/controller/controller_sync.go, ibft/ibft.go, ibft/simulation/main.go, ibft/simulation/scenarios/change_round_speedup.go, ibft/simulation/scenarios/f_1_multi_round.go, ibft/simulation/scenarios/f_1_speedup.go, ibft/simulation/scenarios/far_future_sync.go, ibft/simulation/scenarios/regular.go, ibft/simulation/scenarios/scenario.go, ibft/simulation/scenarios/sync_failover.go, validator/duty_execution.go
=> ibft: remove `ValidatorShare` from `ControllerStartInstanceOptions`

exporter/node_test.go, exporter/storage/storage.go, exporter/storage/validators.go, exporter/storage/validators_test.go, registry/storage/operators.go, registry/storage/operators_test.go
=> Exporter: fix validators/operators query

.gitlab-ci.yml, cli/operator/node.go, exporter/node.go, exporter/validators_metadata.go, migrations/migration_3_clean_operator_node_registry_data.go, migrations/migrations.go, operator/node.go, operator/storage.go, operator/storage_test.go, validator/controller.go, validator/storage/storage.go, validator/storage/storage_test.go
the fix is to start only operator related validator shares
=> Store all network validators fix

eth1/sync.go, migrations/migration_4_clean_exporter_registry_data.go, migrations/migrations.go, storage/kv/badger.go, storage/kv/logger.go, validator/controller.go
https://github.com/bloxapp/ssv/pull/567
https://github.com/bloxapp/ssv/pull/568
=> Stage to Main (v0.1.11 preparation) Part 4

automation/qbft/tests/all_test.go, protocol/v1/qbft/controller/controller_running_instance.go, protocol/v1/qbft/controller/msgqueue_consumer.go, protocol/v1/qbft/msgqueue/iterator_test.go, protocol/v1/qbft/msgqueue/metrics.go, protocol/v1/qbft/msgqueue/post_consensus_msg.go, protocol/v1/qbft/msgqueue/queue.go, protocol/v1/qbft/msgqueue/queue_test.go, protocol/v1/qbft/msgqueue/signed_msg.go
As part of this PR, the following were added/fixed:
- added q size metric per validator
- fix possible drop of messages and simplify pop logic
- renaming and interface alignment
=> QBFT Msg Queue Updates

cli/operator/node.go, eth1/sync.go, ibft/conversion/converters.go, network/discovery/local_service.go, network/p2p/config.go, network/p2p/p2p.go, network/p2p/p2p_setup.go, network/peers/conn_handler.go, network/peers/handshaker.go, network/streams/controller.go, network/topics/controller.go, network/topics/gossipsub_params.go, operator/duties/controller.go, operator/duties/fetcher.go, operator/validator/controller.go, protocol/v1/message/consensus.go, protocol/v1/qbft/controller/duty_execution.go, protocol/v1/qbft/controller/proccess_message.go, protocol/v1/qbft/controller/signature.go, protocol/v1/qbft/instance/instance.go, protocol/v1/sync/commons.go, protocol/v1/sync/handlers/last_change_round.go, protocol/v1/sync/lastdecided/fetcher.go
- align env vars
- change logs to `Warn` instead of `Error`
- clean redundant logs
=> Cleanup and Preparations

cli/operator/node.go, operator/validator/controller.go, operator/validator/controller_test.go, protocol/v1/queue/worker/message_worker.go, protocol/v1/queue/worker/message_worker_test.go
This PR includes the following changes:
- added flags to control msg workers and update default values
- added metric
- aligned worker functions
=> Msg Workers Alignment

automation/qbft/scenarios/on_fork_v1.go, ibft/storage/ibft_store.go, protocol/v1/qbft/controller/controller_decided.go, protocol/v1/qbft/strategy/fullnode/fullnode.go
This PR aligns the decided message processing according to the desired flow as detailed in the following diagram:
=> Decided processing Alignment

.k8/yamls-stage-v1/ssv-node-v2-1-deployment.yml, .k8/yamls-stage/ssv-exporter-v2.yml, .k8/yamls-stage/ssv-exporter.yml, .k8/yamls-stage/ssv-node-10-deployment.yml, .k8/yamls-stage/ssv-node-11-deployment.yml, .k8/yamls-stage/ssv-node-12-deployment.yml, .k8/yamls-stage/ssv-node-9-deployment.yml, .k8/yamls-stage/ssv-node-v2-2-deployment.yml, .k8/yamls-stage/ssv-node-v2-3-deployment.yml, .k8/yamls-stage/ssv-node-v2-4-deployment.yml, .k8/yamls-stage/ssv-node-v2-5-deployment.yml, .k8/yamls-stage/ssv-node-v2-6-deployment.yml, .k8/yamls-stage/ssv-node-v2-7-deployment.yml, .k8/yamls-stage/ssv-node-v2-8-deployment.yml
Updating `p2p.NetworkID` / `NETWORK_ID` in all stage nodes and exporters to `ssv-testnet-stage`.
=> Update Network ID for Stage Nodes

network/forks/v2/pubsub_mapping.go, network/peers/peers_index.go, network/topics/controller_test.go
- modify topics prefix also for forkv2
- change inbound peer limit to 125% of the configured MaxPeers
- fix pubsub test
=> Prepare Stage

eth1/abi_parser.go, eth1/abi_parser_test.go, eth1/abiparser/Legacy.go, eth1/abiparser/v1.go, eth1/abiparser/v2.go, eth1/goeth/goETH.go, eth1/goeth/goETH_test.go, eth1/sync.go, eth1/sync_test.go, network/p2p/config.go, operator/storage/storage.go, operator/validator/controller.go, operator/validator/event_handler.go, operator/validator/utils.go, registry/storage/operators.go
this PR includes:
- the logic checking for malformed events
- OperatorRemoved event parsing&handling
=> eth1 v2 malformed events

protocol/v1/qbft/instance/instance.go, protocol/v1/qbft/instance/timer.go
Resolve https://github.com/bloxapp/ssv/issues/615
=> Use Context to Kill QBFT Instance

protocol/v1/qbft/instance/commit.go, protocol/v1/qbft/instance/commit_test.go
Add round validation for commit message
=> Round validation

network/p2p/config.go, network/p2p/p2p.go, network/p2p/p2p_pubsub.go, network/p2p/p2p_setup.go, network/p2p/p2p_test.go, network/p2p/test_utils.go, network/peers/scores_test.go, network/topics/controller.go, network/topics/sub_filter.go, operator/duties/fetcher.go
- added a flag (`P2P_LOG`) to turn on/off network debug logs
- reduced redundant + overloading logs
=> Network Logs

network/p2p/p2p_setup.go, network/topics/gossipsub_params.go, network/topics/pubsub.go
This PR contains several fixes and alignments in the network layer:
* created ID Service only if it wasn't created by libp2p Host
* increased gossip degree parameters for better propagation of message
* modified iwant/ihave cache
* increased `validateThrottle` (4096)
* modified subscriptions limit (128 subnets + 1 decided topic)
=> Network Fixes

network/p2p/p2p_setup.go, network/topics/gossipsub_params.go, network/topics/pubsub.go
* created ID Service only if it wasn't created by libp2p Host
* increased gossip degree parameters for better propagation of message
* modified iwant/ihave cache
* increased `validateThrottle` (4096)
* modified subscriptions limit (128 subnets + 1 decided topic)
=> Network Fixes (#653)

.k8/yamls-stage/ssv-node-10-deployment.yml, .k8/yamls-stage/ssv-node-11-deployment.yml, .k8/yamls-stage/ssv-node-12-deployment.yml, .k8/yamls-stage/ssv-node-9-deployment.yml, network/p2p/config.go
This PR changes default value of the following configs:
- changed bootnode ENR
- changed network id to `shifu` (and `shifu-stage`)
=> Config Alignment (v2)

monitoring/grafana/dashboard_ssv_operator.json
=> Grafana: Fix broken data source

ibft/storage/ibft_store.go, ibft/storage/ibft_store_test.go, operator/validator/event_handler.go, operator/validator/storage_test.go, protocol/v1/qbft/controller/controller.go, protocol/v1/qbft/storage/ibft_store.go, protocol/v1/qbft/storage/test_utils.go
Clean last change round didn't remove as expected. 
fixed cleaning & add test
=> fix clean last change round

.gitlab-ci.yml, ibft/IBFT.md, ibft/valcheck/value_check.go, protocol/v1/qbft/controller/msgqueue_consumer.go, protocol/v1/qbft/controller/msgqueue_consumer_test.go, protocol/v1/qbft/instance/change_round.go, protocol/v1/qbft/instance/change_round_test.go, protocol/v1/qbft/instance/forks/fork.go, protocol/v1/qbft/instance/forks/genesis/fork.go, protocol/v1/qbft/instance/instance.go, protocol/v1/qbft/instance/proposal.go, protocol/v1/qbft/instance/proposal_test.go, protocol/v1/qbft/types.go, protocol/v1/qbft/validation/changeround/upon_full_quorum.go, protocol/v1/qbft/validation/pipelines.go, protocol/v1/qbft/validation/proposal/validate.go, protocol/v1/qbft/validation/proposal/validate_test.go, protocol/v1/qbft/validation/value_check.go, spectest/qbft/qbft_mapping_test.go
Depends on https://github.com/bloxapp/ssv/pull/682
=> Rename pre-prepare to proposal

ekm/signer_key_manager_test.go, exporter/README.md, ibft/storage/ibft_store.go, monitoring/README.md, monitoring/grafana/dashboard_ssv_operator.json, network/p2p/p2p_test.go, protocol/v1/qbft/controller/forks/genesis/fork.go, protocol/v1/qbft/controller/metrics.go, protocol/v1/qbft/instance/change_round_test.go, protocol/v1/qbft/instance/commit.go, protocol/v1/qbft/instance/commit_test.go, protocol/v1/qbft/instance/forks/genesis/fork.go, protocol/v1/qbft/instance/instance.go, protocol/v1/qbft/instance/metrics.go, protocol/v1/qbft/instance/pre_prepare_test.go, protocol/v1/qbft/instance/prepare.go, protocol/v1/qbft/instance/prepare_test.go, protocol/v1/qbft/metrics.go, protocol/v1/qbft/msgqueue/metrics.go, protocol/v1/qbft/types.go, protocol/v1/qbft/validation/changeround/validate_justification.go, protocol/v1/qbft/validation/changeround/validate_justification_test.go, protocol/v1/qbft/validation/commit/validate_test.go, protocol/v1/qbft/validation/prepare/validate_test.go, protocol/v1/qbft/validation/preprepare/validate_test.go, protocol/v1/qbft/validation/signedmsg/msg_lambda.go, protocol/v1/qbft/validation/signedmsg/msg_lambda_test.go, utils/format/identifier.go
Depends on https://github.com/bloxapp/ssv/pull/682
=> Rename lambda to identifier

exporter/api/server.go, monitoring/metrics/handler.go, network/p2p/p2p_pubsub.go, network/p2p/p2p_setup.go, network/topics/metrics.go, network/topics/msg_validator.go, network/topics/msg_validator_test.go, network/topics/pubsub.go, operator/validator/controller.go, operator/validator/router.go, utils/boot_node/node.go
This PR consists of several changes that will optimize message processing:
* removed cache and thus reducing encoding, msgID (does sha256) and go-cache that we have on every message, so it won't bottle-necked the system
* enable topic validator and save reference for the decoded message object (to reuse decoded object)
* reduced encoding in the msg router level as we do it once in the msg validator
* increased pubsub params that limits msg rate
* increased msg workers count
=> Message Processing Optimization

protocol/v1/qbft/controller/controller.go, protocol/v1/qbft/controller/controller_running_instance.go, protocol/v1/qbft/controller/msgqueue_consumer_test.go, protocol/v1/qbft/instance/change_round.go, protocol/v1/qbft/instance/change_round_test.go, protocol/v1/qbft/instance/forks/genesis/fork.go, protocol/v1/qbft/instance/instancer.go
This PR implements https://github.com/bloxapp/SIPs/pull/10 (**TODO: SIP approval**):
* continuously get highest change round
=> Change Round Sync Triggers

protocol/v1/qbft/controller/controller.go
* Rollback controller state so it could try to initialize again (resolve #708)
=> Fix controller state in case it couldn't find min peers

.gitignore, Makefile, docker-compose.yaml
Removed from:
- `Makefile`
- `docker-compose.yaml`
- `.gitignore`
=> Remove exporter leftovers

network/p2p/config.go
Added a second bootnode as default config for `shifu` testnet
=> Add Bootnode

network/p2p/p2p_sync.go, operator_v2/validator/controller.go, protocol/v2/qbft/instance/instance.go, protocol/v2/qbft/instance/round_change.go, protocol/v2/qbft/instance/timeout.go, protocol/v2/qbft/roundtimer/timer.go, protocol/v2/qbft/roundtimer/timer_test.go, protocol/v2/ssv/runner/runner.go
* patched changes from spec:
* https://github.com/bloxapp/ssv-spec/pull/100
* https://github.com/bloxapp/ssv-spec/pull/105
* https://github.com/bloxapp/ssv-spec/pull/109
* implemented new `Timer`
* avoid blocking procedures on instance start (broadcast, sync change rounds)
* register `onTimeout` handler in duty runner
* change round sync fixes
=> Spec alignment: Change Round

exporter/api/msg.go, ibft/storage/store_test.go, network/forks/genesis/encoding_test.go, network/forks/genesis/pubsub_cfg_test.go, protocol/v2/message/msg.go, protocol/v2/qbft/spectest/msg_processing_type.go
Replacing TOMessageID func with spec same func
=> Deprecate ToMessageID Func

.github/workflows/full-test.yml, Makefile
* makefile: added `spec-test` cmd
* ci: separated `spec-test` from `full-test`
=> CI: spec testing

.github/workflows/full-test.yml, .github/workflows/integration-test.yml, .github/workflows/lint.yml, .github/workflows/spec-test.yml, .github/workflows/test-cov.yml, .github/workflows/unit-test.yml, Makefile
* added workflows for unit, spec, integration, and all tests
* added makefile cmds for testing unit or all
=> CI: aligned workflows by test type

.gitlab-ci.yml, .k8/yamls-stage-v1/ssv-node-v2-1-deployment.yml, .k8/yamls-stage/ssv-node-10-deployment.yml, .k8/yamls-stage/ssv-node-11-deployment.yml, .k8/yamls-stage/ssv-node-12-deployment.yml, .k8/yamls-stage/ssv-node-9-deployment.yml, .k8/yamls-stage/ssv-node-v2-2-deployment.yml, .k8/yamls-stage/ssv-node-v2-3-deployment.yml, .k8/yamls-stage/ssv-node-v2-4-deployment.yml, .k8/yamls-stage/ssv-node-v2-5-deployment.yml, .k8/yamls-stage/ssv-node-v2-6-deployment.yml, .k8/yamls-stage/ssv-node-v2-7-deployment.yml, .k8/yamls-stage/ssv-node-v2-8-deployment.yml
Updated stage nodes: `ssv-node-v2-*` and `ssv-node-*`
=> CI: update stage deploy on all nodes

Makefile
As race is checked in each test suite independently.
=> Disable race flag in full-test

README.md, docs/OPERATOR_GETTING_STARTED.md, docs/THREADING.md, docs/specs/NETWORKING.md, exporter/README.md
=> Fix: typos

logging/field_wrapers.go
https://bloxxx.atlassian.net/browse/IO1-2507
Feel beneficial 🤡
=> Io1 2507 field wrappers

ekm/signer_storage.go, exporter/api/decided/stream.go, ibft/storage/store.go, identity/store.go, network/discovery/dv5_bootnode.go, network/discovery/dv5_test.go, network/discovery/local_service.go, network/discovery/options.go, network/p2p/forks.go, network/p2p/p2p_test.go, network/p2p/test_utils.go, network/topics/controller_test.go, network/topics/pubsub.go, network/topics/sub_filter.go, operator/validator/controller.go, operator/validator/metrics.go, protocol/v2/queue/worker/message_worker.go, protocol/v2/ssv/validator/non_committee_validator.go, protocol/v2/sync/handlers/decided_history.go, protocol/v2/sync/handlers/last_decided.go, utils/boot_node/node.go
https://bloxxx.atlassian.net/browse/IO1-2593
change `logger.With("who", "xxx")` to `logger.Named("xxx")`
=> replace usage of "who" field with named logger pattern

cli/operator/node.go, eth1/goeth/goETH.go, exporter/api/server.go, ibft/storage/store.go, monitoring/metrics/handler.go, network/discovery/local_service.go, network/p2p/config.go, network/p2p/forks.go, network/p2p/p2p.go, network/p2p/p2p_setup.go, network/topics/pubsub.go, operator/duties/controller.go, utils/boot_node/node.go
https://bloxxx.atlassian.net/browse/IO1-2508
=> clean up few log messages

Makefile, integration/qbft/tests/round_change_test.go, integration/qbft/tests/scenario_test.go, network/p2p/p2p_setup.go, operator/validator/controller.go, protocol/v2/qbft/roundtimer/timer.go, protocol/v2/ssv/runner/runner.go, protocol/v2/ssv/validator/msgqueue_consumer.go, protocol/v2/ssv/validator/startup.go, protocol/v2/ssv/validator/timer.go, protocol/v2/ssv/validator/validator.go
Fixes for race conditions in https://github.com/bloxapp/ssv/pull/830
See comments for explanation of race conditions
=> IO1-2633: Fix race conditions in integration tests

ekm/eth_key_manager_signer.go, ekm/signer_storage.go, ekm/signer_storage_test.go, go.mod, go.sum, utils/boot_node/node.go
- align to [EKM](https://github.com/bloxapp/eth2-key-manager/releases/tag/v1.3.0-rc.0) 
- support versionedBeaconBlock (capella)
=> Align ekm v1.3.0

logging/fields/fields.go, operator/duties/controller.go, protocol/v2/ssv/validator/msgqueue_consumer.go, protocol/v2/ssv/validator/timer.go
* add log when message is pushed to queue
* change pop message log to be consistent
=> Queue push logging

.dockerignore, Dockerfile, hooks/build
* added `hooks/build` script to provide APP_VERSION
=> Docker Hub Hooks (#915)

.gitlab-ci.yml, operator/fee_recipient/controller.go, operator/fee_recipient/controller_test.go, operator/validator/controller.go, protocol/v2/ssv/runner/validator_registration.go, protocol/v2/ssv/testing/runner.go, protocol/v2/ssv/validator/non_committee_validator.go, scripts/spec-alignment/differ.config.yaml
This PR reverts a spec alignment change, because it causes a nil dereference panic.
=> fix: missing Controller in ValidatorRegistrationRunner

docs/specs/NETWORKING.md
current url is broken (404 response code)
=> fix: messages.go url from ssv-spec repo

.gitlab-ci.yml, cli/operator/node.go, eth1/mock_sync.go, exporter/api/query_handlers_test.go, migrations/migration_0_example.go, migrations/migrations.go, network/peers/connections/mock/mock_storage.go, operator/duties/controller.go, operator/duties/fetcher_test.go, operator/fee_recipient/controller.go, operator/fee_recipient/controller_test.go, operator/fee_recipient/mocks/controller.go, operator/node.go, operator/slot_ticker/mocks/ticker.go, operator/storage/storage.go, operator/storage/storage_test.go, operator/validator/controller.go, operator/validator/event_handler.go, operator/validator/mocks/controller.go, protocol/v2/blockchain/beacon/mock_client.go, protocol/v2/blockchain/beacon/mock_validator_metadata.go, protocol/v2/blockchain/beacon/validator_metadata_test.go, registry/storage/shares.go, registry/storage/shares_test.go
This PR rewrites the shares storage implementation to maintain a replica of the stored shares in-memory, skipping the database entirely in read operations.
=> Share Caching

.gitlab-ci.yml
=> Revert `.gitlab.yml`

.golangci.yaml, cli/operator/node.go, exporter/api/conn.go, network/p2p/p2p_sync.go, network/peers/connections/handshaker.go, network/peers/peers_index.go, network/topics/controller.go, storage/kv/gc.go
- Fix `%W` verb
- Error type assertion doesn't work with wrapped errors, `errors.As` should be used instead
- Comparison using `==` or `!=` doesn't work with wrapped errors, `errors.Is` should be used instead
=> Fix error handling issues

operator/validator/event_handler.go
TODO: the same for the rest of the events
=> Always Log Events

eth/eventdatahandler/event_data_handler_test.go, eth/eventdatahandler/task_executor_test.go
=> Eth1 refactor more tests

cli/operator/node.go, ekm/eth_key_manager_signer.go, ekm/signer_storage.go, ekm/signer_storage_test.go, eth/eventdatahandler/event_data_handler_test.go, eth/eventdispatcher/event_dispatcher_test.go, exporter/api/query_handlers_test.go, ibft/storage/store.go, ibft/storage/stores.go, identity/store.go, migrations/migrations.go, monitoring/metrics/handler.go, network/peers/connections/mock/mock_storage.go, operator/fee_recipient/controller_test.go, operator/node.go, operator/storage/storage.go, operator/validator/controller.go, protocol/v2/qbft/testing/storage.go, protocol/v2/testing/test_utils.go, registry/storage/events.go, registry/storage/operators.go, registry/storage/recipients.go, registry/storage/shares.go, storage/basedb/storage.go, storage/kv/badger.go, storage/kv/badger_test.go, storage/kv/txn.go
Changes according to https://github.com/bloxapp/ssv/pull/1020#discussion_r1271399377
=> update storage interfaces

ekm/signer_key_manager_test.go
This test was trying to change the encryption key by overwriting the last character with 'a', however sometimes the last character was already 'a' and the key remained unchanged.
This PR now generates another key instead of trying to modify the same one.
=> fix: encryption key collusion in `TestEncryptedKeyManager`

operator/fork.go, operator/node.go
Use Fatal instead of Panic, do that in parent method
=> [Audit Suggestion 1] Do not use panics on fork

config/config.example.yaml
Added comments and some fields that were missing.
=> Revamp `config.example.yaml`

operator/duties/scheduler_test.go, operator/duties/validatorregistration.go
* fix: jammed `indicesChange` channel
---------
=> fix: jammed `indicesChange` channel (#1131)

Makefile, cli/bootnode/boot_node.go, cli/operator/node.go, cmd/ssvnode/main.go
looks like this now - 
```
2023-11-18T20:14:37.699299Z	[35mINFO[0m	starting ssv-node { "version":  "v1.0.0-rc.2-44-g2409736e-stage-2409736e1e1b22e1c6e882821075eb38cc076dde" }
```
=> Feat/ log branch and commit ver

cli/operator/node.go, network/p2p/config.go, network/p2p/p2p.go, network/p2p/p2p_pubsub.go
* fix: stale operator ID in `p2pNetwork`
---------
=> v1.2.1 (includes #1229)

.dockerignore, Dockerfile, Makefile, cmd/ssvnode/main.go
small change before we release the version
=> Include git commit/version in Docker build (#1231)

operator/duties/attester_test.go, operator/duties/mocks/scheduler.go, operator/duties/proposer.go, operator/duties/proposer_test.go, operator/duties/scheduler.go, operator/duties/sync_committee.go, operator/duties/sync_committee_test.go, operator/validator/controller.go, operator/validator/controller_test.go
* [fix: get own sync committee duties after validators setup.](https://github.com/bloxapp/ssv/pull/1306/commits/6579b98c827ef3ef4e7b18320ab295fe5ee779f9)
=> v1.3.0-rc.1

go.mod, go.sum
=> update to use patched fixed go-eth2-client

network/p2p/p2p_setup.go, network/peers/connections/filters.go, network/peers/connections/filters_test.go, network/peers/connections/handshaker.go
This PR reverts back the accidental removal of the domain type check merged at https://github.com/ssvlabs/ssv/pull/1284
=> fix: (handshake) missing domain type check

protocol/v2/ssv/validator/committee.go, protocol/v2/ssv/validator/committee_queue.go
This change addresses bug with dropping future msg as queue doesn't exist at the time of arrival
=> create queue for future msgs

Dockerfile
---
name: PR template
about: PR template to make sure devs run the E2E suite on the branch
title: ''
labels: 
assignees: ''
---
=> fix: (Dockerfile) dnsutils installation

message/validation/partial_validation.go, message/validation/validation.go
=> message validation: use maxPartialSignatureMsgsSize from block with all constants

network/p2p/test_utils.go
https://github.com/ssvlabs/ssv/pull/1393#discussion_r1667678408
=> Fix commented-out code in network/p2p/test_utils.go

go.mod, go.sum
=> go.mod: remove gods dependency

registry/storage/validatorstore.go
=> validatorStore: fix bug with indices on share update

message/validation/common_checks.go, message/validation/errors.go
Improve clarity of the check by adding a comment
=> message validation: add comments when getting first validator index

integration/qbft/tests/regular_test.go, integration/qbft/tests/round_change_test.go, integration/qbft/tests/scenario_test.go, integration/qbft/tests/setup_test.go, message/validation/genesis/validation_test.go, network/discovery/dv5_service_test.go, operator/validator/controller_test.go, registry/storage/shares_test.go
- Fix [TestHandleNonCommitteeMessages](https://github.com/ssvlabs/ssv/commit/23f07f50eefc092436e3856790cb98fff88b338f)
- Fix [TestCheckPeer](https://github.com/ssvlabs/ssv/pull/1534/commits/82c6801b60ec40b30ac0cdf8cddca0ba2d64456b)
- Skip failing tests
=> Pass unit tests CI

operator/duties/scheduler.go
Revive deleted scheduler validator registration handler 
closes https://github.com/ssvlabs/ssv/issues/1548
=> Resurrect Validator Registration Handler

message/validation/genesis/validation.go, network/p2p/p2p_genesis.go, operator/validator/controller.go, protocol/genesis/ssv/runner/aggregator.go, protocol/genesis/ssv/runner/attester.go, protocol/genesis/ssv/runner/proposer.go, protocol/genesis/ssv/runner/runner.go, protocol/genesis/ssv/runner/sync_committee.go, protocol/genesis/ssv/runner/sync_committee_aggregator.go, protocol/genesis/ssv/runner/validator_registration.go, protocol/genesis/ssv/runner/voluntary_exit.go, protocol/genesis/ssv/spectest/ssv_mapping_test.go, protocol/genesis/ssv/testing/runner.go, protocol/v2/ssv/queue/messages.go
1. Broadcast to validator topic
2. Bad error check in message validation
3. Use correct domain type in pre-fork runners
=> fix: 3 bugs in pre-fork

message/validation/genesis/partial_validation.go, message/validation/genesis/validation.go, message/validation/genesis/validation_test.go
closes https://github.com/ssvlabs/ssv/issues/1518
- re-enables partial sig msg validations
- re-enable topics msg val check
- re-enables genesis msg val tests
=> Re-enable msg validation

operator/validator/controller.go, operator/validator/task_executor.go, operator/validators/validator_container.go
This change allows to update genesis validator shares as well as new shares on any update
=> fix: update both Genesis & Alan shares

Makefile, integration/qbft/tests/regular_test.go, integration/qbft/tests/round_change_test.go, integration/qbft/tests/scenario_test.go, integration/qbft/tests/setup_test.go, integration/qbft/tests/test_duty.go, network/p2p/p2p_pubsub.go, network/p2p/p2p_test.go, network/p2p/p2p_validation_test.go, network/p2p/test_utils.go, network/topics/controller_test.go
Closes #1552
- fix [TestTopicManager](https://github.com/ssvlabs/ssv/pull/1539/commits/bcb319cb033ef84579bff60a0049e6332bc71e77)
- fix p2p tests
- make integration tests runnable, 
- however, they don't pass, but since they are broken on `main`, this is out of scope of this PR
=> Fix skipped unit tests

network/p2p/p2p_validation_test.go, network/p2p/test_utils.go
- fix `TestP2pNetwork_MessageValidation`
=> fix flaky TestP2pNetwork_MessageValidation

operator/duties/committee_test.go
=> fix flaky TestScheduler_Committee_Indices_Changed_Attester_Only

cli/operator/node.go, network/discovery/dv5_service.go, network/discovery/dv5_service_test.go, network/p2p/config.go, network/p2p/p2p.go, network/p2p/test_utils.go, operator/node.go, registry/storage/shares.go
this fix https://github.com/ssvlabs/ssv/issues/1565 (#1493) provide custom domain and trusted peers
We have decided custom domain isn't relevant after alan fork so this change means custom domain overrides genesis domain and after alan will fork everyone will be on the same domain.
=> Custom DomainType and TrustedPeers (Alan)

protocol/genesis/qbft/instance/commit.go, protocol/genesis/qbft/instance/proposal.go, protocol/genesis/qbft/instance/round_change.go, protocol/genesis/qbft/instance/timeout.go, protocol/v2/qbft/instance/commit.go, protocol/v2/qbft/instance/proposal.go, protocol/v2/qbft/instance/round_change.go, protocol/v2/qbft/instance/timeout.go, utils/boot_node/node.go, utils/keys.go
=> chore: change hyphens to underscores in log labels

protocol/v2/qbft/instance/prepare.go
=> FIX: "got prepare message" Log 

operator/duties/attester.go, operator/duties/attester_genesis_test.go, operator/duties/attester_test.go, operator/duties/committee_test.go, operator/duties/proposer.go, operator/duties/proposer_genesis_test.go, operator/duties/proposer_test.go, operator/duties/sync_committee.go, operator/duties/validatorregistration.go, operator/duties/voluntary_exit_genesis_test.go
closes https://github.com/ssvlabs/ssv/issues/1607
also, this PR introducing a fix to a bug where the handler starts in preparation epochs range that will not trigger next period duties
=> Duty Scheduler Fork Related Missing Tests

operator/duties/committee_test.go
closes https://github.com/ssvlabs/ssv/issues/1580
=> Implement TestScheduler_Committee_Early_Block

protocol/v2/ssv/validator/committee_queue.go
=> fix: don't read post-consensus message before decided

operator/duties/attester_genesis_test.go, operator/duties/attester_test.go, operator/duties/committee_test.go
=> Fix: flaky duty scheduler tests

eth/ethtest/eth_e2e_test.go, eth/ethtest/validator_added_test.go, eth/ethtest/validator_exited_test.go, eth/ethtest/validator_removed_test.go, eth/eventhandler/event_handler_test.go, eth/eventhandler/handlers.go, message/validation/genesis/validation.go, message/validation/validation.go, message/validation/validation_test.go, network/p2p/p2p_genesis.go, network/p2p/p2p_pubsub.go, operator/duties/scheduler.go, operator/duties/scheduler_mock.go, operator/storage/storage.go, operator/validator/controller.go, operator/validator/controller_test.go, operator/validator/mocks/controller.go, protocol/v2/blockchain/beacon/mock_validator_metadata.go, protocol/v2/blockchain/beacon/validator_metadata.go, protocol/v2/blockchain/beacon/validator_metadata_test.go, protocol/v2/ssv/validator/non_committee_validator.go, protocol/v2/types/ssvshare.go, registry/storage/mocks/validatorstore.go, registry/storage/shares.go, registry/storage/shares_test.go, registry/storage/validatorstore.go, registry/storage/validatorstore_test.go
closes https://github.com/ssvlabs/ssv/issues/1594
=> Validator Store tests

operator/duties/committee.go, operator/duties/scheduler.go, operator/duties/scheduler_test.go, operator/validator/controller.go, protocol/v2/ssv/validator/committee.go, protocol/v2/ssv/validator/committee_queue.go, protocol/v2/ssv/validator/duty_executer.go, protocol/v2/types/ssvshare.go
Fix committee duty ID logging.
- The PR introducing a fix to #1711 and his duplicate (https://github.com/ssvlabs/ssv/issues/1692) 
- this commit https://github.com/ssvlabs/ssv/pull/1704/commits/992a85accb349cd41ac885b272bb10b140e21424
resolves partially  https://github.com/ssvlabs/ssv/issues/1666
=> fix: committee duty id log

scripts/differ/diff.go, scripts/differ/go.mod, scripts/differ/go.sum, scripts/differ/main.go, scripts/differ/parser.go, scripts/differ/ui/package-lock.json, scripts/differ/ui/package.json, scripts/differ/ui/pages/index.tsx, scripts/spec-alignment/differ.config.yaml
This PR removes the usage of the Go `unidiff` package and replaces it with `git diff` command execution, because the former was producing incorrect diffs.
`a.go`
```go
func (b *BaseRunner) baseConsensusMsgProcessing(runner Runner, msg *SignedSSVMessage, decidedValue Encoder) (bool, Encoder, error) {
prevDecided := false
if b.hasRunningDuty() && b.State != nil && b.State.RunningInstance != nil {
prevDecided, _ = b.State.RunningInstance.IsDecided()
}
if prevDecided {
return true, nil, errors.New("not processing consensus message since consensus has already finished")
}
decidedMsg, err := b.QBFTController.ProcessMsg(msg)
if err != nil {
return false, nil, err
}
if !b.hasRunningDuty() {
return false, nil, nil
}
if decideCorrectly, err := b.didDecideCorrectly(prevDecided, decidedMsg); …
```
=> fix: (differ) incorrect diffs

cli/operator/node.go, cli/operator/node_test.go, migrations/migration_4_configlock_add_alan_fork_to_network_name.go, migrations/migrations.go, networkconfig/config.go, operator/storage/config_lock.go, operator/storage/config_lock_test.go
=> feat: prevent incompatible alan version downgrade

.golangci.yaml, ekm/signer_storage.go, integration/qbft/tests/setup_test.go, operator/keys/rsa_linux_test.go
port fixes from the PRs below to the main branch
https://github.com/ssvlabs/ssv/pull/1627
https://github.com/ssvlabs/ssv/pull/1647
=> lint: fix issues after version upgrade (main)

network/p2p/p2p.go, network/p2p/p2p_setup.go, network/peers/conn_manager.go, network/peers/conn_manager_test.go, network/peers/connections/conn_gater.go, network/peers/connections/filters.go, network/peers/gossip_score_index_test.go, network/peers/gossipsub_score_index.go, network/peers/index.go, network/peers/peers_index.go, network/peers/subnets.go, network/topics/controller_test.go, network/topics/pubsub.go, network/topics/scoring.go
This PR drops bad or irrelevant peers, similarly to https://github.com/ssvlabs/ssv/pull/1707, but for the main branch.
=> Drop bad or irrelevant peers (main)

.gitlab-ci.yml, Dockerfile
Fixes some issues when deploying to production.
=> fix: dockerfile dnsutils and gitlabci config

exporter/api/msg.go
Fill `FullData.Duty.PubKey` because API users need it
=> exporter: add pubkey to FullData on API response

network/discovery/dv5_service.go
This is a temporary version of https://github.com/ssvlabs/ssv/pull/1803 for until it's merged.
=> chore: (discovery) reduce "skipped peers" logs

operator/duties/scheduler.go
=> Increase block propagation delay

docs/OPERATOR_GETTING_STARTED.md, docs/specs/NETWORKING.md
=> fix: (docs) typos (#1830)

utils/hashmap/hashmap_test.go
I've noticed that test(s) in `github.com/ssvlabs/ssv/utils/hashmap` package consume up to 8GB of memory when running, sometimes it even results in the test being killed by OS:
```
ok  	github.com/ssvlabs/ssv/utils/format	1.012s	coverage: 70.8% of statements
PASS
coverage: 100.0% of statements
signal: killed
FAIL	github.com/ssvlabs/ssv/utils/hashmap	9.973s
ok  	github.com/ssvlabs/ssv/utils/rsaencryption	1.895s	coverage: 56.8% of statements
```
There seems to be a memory leak (creating `Timer` objects in almost infinite loop that is forcefully broken by Test terminating its run). This PR fixes it, and cleans up a bit.
I've also checked all other places in this repo that could have had similar issues (when combining `for{}`, `select`, `time.After`) and found only 1 other test affected by …
=> tests: hashmap optimize memory usage

message/validation/partial_validation.go
closes https://github.com/ssvlabs/ssv/issues/1854
=> fix(message/validation): add missing return

protocol/v2/qbft/controller/controller.go, protocol/v2/qbft/controller/controller_test.go, protocol/v2/qbft/controller/timer.go, protocol/v2/qbft/instance/commit.go, protocol/v2/qbft/instance/instance.go, protocol/v2/qbft/instance/metrics.go, protocol/v2/qbft/instance/observability.go, protocol/v2/qbft/instance/prepare.go, protocol/v2/qbft/instance/proposal.go, protocol/v2/qbft/instance/round_change.go, protocol/v2/qbft/instance/timeout.go, protocol/v2/qbft/spectest/controller_type.go, protocol/v2/qbft/spectest/msg_processing_type.go, protocol/v2/qbft/spectest/timeout_type.go, protocol/v2/ssv/runner/aggregator.go, protocol/v2/ssv/runner/committee.go, protocol/v2/ssv/runner/proposer.go, protocol/v2/ssv/runner/runner.go, protocol/v2/ssv/runner/sync_committee_aggregator.go, protocol/v2/ssv/validator/events.go
**Metrics added**
- `ssv.validator.stage.duration` (`ssv.validator.stage`, `ssv.runner.role`,  `ssv.validator.duty.round` attributes)
**Metrics removed**
- `ssv_validator_instance_stage_duration_seconds ` (`stage` label)
- `ssv_qbft_instance_round` (`roleType` label)
=> chore(metrics): OTeL  - QBFT component instrumentation

eth/eventhandler/handlers.go, operator/duties/attester.go, operator/duties/attester_genesis_test.go, operator/duties/attester_test.go, operator/duties/committee.go, operator/duties/committee_test.go, operator/duties/scheduler.go, operator/duties/scheduler_mock.go, operator/duties/sync_committee.go, operator/duties/sync_committee_genesis_test.go, operator/duties/sync_committee_test.go, protocol/v2/types/ssvshare.go
close https://github.com/ssvlabs/ssv/issues/1885
=> fix: `MinParticipationEpoch` protection [main]

protocol/v2/queue/worker/message_worker.go
This metric is reporting data only on Exporter nodes
=> chore(metrics): Remove message worker metric

operator/validator/controller.go, operator/validator/observability.go
**Metrics added**
- `ssv.validator.validators.active`
**Metrics changed**
- `ssv.validator.validators`-> `ssv.validator.validators.per_status`
=> feat(metrics) OTeL - implement active validator count gauge

README.md, docs/specs/NETWORKING.md
Duplicate of #1858 but for main.
=> chore(readme): redesign (main)

network/discovery/dv5_service.go, network/discovery/subnets.go, network/p2p/p2p_pubsub.go, network/p2p/p2p_setup.go
Avoid logging zero-filled subnets
=> fix(p2p): improve active subnets handling and logging

beacon/goclient/aggregator.go, beacon/goclient/attest.go, beacon/goclient/committee_subscribe.go, beacon/goclient/goclient.go, beacon/goclient/proposer.go, beacon/goclient/signing.go, beacon/goclient/sync_committee.go, beacon/goclient/sync_committee_contribution.go, beacon/goclient/validator.go, beacon/goclient/voluntary_exit.go, eth/executionclient/execution_client.go, protocol/v2/ssv/runner/committee.go
close https://github.com/ssvlabs/ssv/issues/1783
=> chore: improve consensus/execution layer clients logging and error handling

network/network.go, network/p2p/p2p_setup.go, operator/validator/controller.go, operator/validator/controller_test.go, operator/validator/mocks/controller.go
fix https://github.com/ssvlabs/ssv/issues/1961
=> fix(exporter): ensure exporter node fetch metadata for all validators

operator/validator/controller.go
GasLimit config and ENV mentioning Experimental and have detailed help message.
=> chore: rename gas limit and add help

scripts/differ/parser.go
This is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor: using slices.Contains to simplify the code

eth/executionclient/multi_client.go
=> eth/executionclient: fix panic in multi-client

migrations/migration_5_share_gob_to_ssz.go
A follow-up to https://github.com/ssvlabs/ssv/pull/2002 to resolve the issue I mentioned in https://github.com/ssvlabs/ssv/pull/2002#discussion_r1926891238 - now that **migration_5** has been **completed** on all **stage** nodes it has been **applied** we can switch to more strict sanity check (which I think is desirable for prod nodes).
=> migrations: enhance sanity check in migration_5

beacon/goclient/dataversion.go, beacon/goclient/dataversion_test.go, beacon/goclient/goclient.go
---
name: PR template
about: PR template to make sure devs run the E2E suite on the branch
title: ''
labels: 
assignees: ''
---
=> fix: conditional handling of Electra fork epoch

beacon/goclient/dataversion_test.go
---
name: PR template
about: PR template to make sure devs run the E2E suite on the branch
title: ''
labels: 
assignees: ''
---
=> fix: update expectedElectra value in TestCheckForkValues

network/discovery/dv5_service.go, network/discovery/forking_dv5_listener.go, network/discovery/forking_dv5_listener_test.go
Part of PRs that will replace https://github.com/ssvlabs/ssv/pull/1308
=> refactor(discovery): remove unused network config from forkingDV5Listener

beacon/goclient/WAD.md, beacon/goclient/attest.go, beacon/goclient/attest_test.go, beacon/goclient/committee_subscribe.go, beacon/goclient/events.go, beacon/goclient/events_test.go, beacon/goclient/goclient.go, beacon/goclient/options.go, beacon/goclient/proposer.go, beacon/goclient/sync_committee.go, doppelganger/README.md, e2e/logs_catcher/logs.go, eth/design.md, operator/validator/controller.go, protocol/v2/blockchain/beacon/client.go, protocol/v2/ssv/validator/non_committee_validator.go, protocol/v2/ssv/validator/startup.go
Resolves merge conflits for https://github.com/ssvlabs/ssv/pull/2175
=> Stage <- Main

eth/eventhandler/handlers.go
Add expected nonce log to debug registrations with incorrect nonce
=> eventhandler: log expected nonce on malformed event

protocol/v2/ssv/validator/committee_queue_test.go
Apparently the aggregate PR that was supposed to sync **stage** branch with changes from **main** -https://github.com/ssvlabs/ssv/pull/2255 - didn't have its own pipeline running automatically, so that pipeline was triggered only when https://github.com/ssvlabs/ssv/pull/2255 got merged into **stage** branch, and it broke.
The root cause is that https://github.com/ssvlabs/ssv/pull/2255 contains https://github.com/ssvlabs/ssv/pull/2199 that's targeting **main** branch and hence it doesn't compile with some code in **stage** branch.
This PR fixes **stage** branch pipelines by adapting the changes in https://github.com/ssvlabs/ssv/pull/2199 to work with **stage** code version.
=> compilation: fix due to skipped pipeline

ssvsigner/README.md
**Description**: When the protocol operates with a local key manager, a local slashing database is used. This database functions as the
main protection against slashing events. In the case that the database goes down or gets erased for any reason, if there is no proper
backup, the slashing history will be erased. Continuing the operation after this point can cause slashing events.
**Recommendation**: Consider outlining that in user-facing documentation. Also consider various backup options to recover the
database if it goes down or get erased.
For now, we only update the docs
=> [SSV-19] ssvsigner: Local Database Is a Single Point of Failure

ssvsigner/keys/rsa_linux.go
> The `once.Do()` ensures that this function only runs once. However, the `err` variable is within this
`checkCachePrivkey()` scope only. In other words, a local `err` variable is captured by the closure passed to `sync.Once.Do()`.
If `rsaPrivateKeyToOpenSSL()` fails during the first invocation, `err` is set accordingly. But on subsequent calls,
`sync.Once.Do()` does not re-run the closure and a new local `err` is initialized to `nil`, causing `checkCachePrivkey` to return
`(cachedPrivKey=nil, err=nil)`. This results in `SignRSA()` being called with a `nil` OpenSSL key handle, likely leading to a
panic.
=> [SSV-6] ssvsigner: Flawed Error Caching in checkCachePrivkey() Leads to Suppressed Errors and Potential Panic

migrations/migration_2_encrypt_shares.go
The PR adds a comment that account overwriting is intentional
=> [SSV-12] ssvsigner: Local Signer Account Overwrite Risk

docs/TRACES.md
Some the queries described in this PR would only work with #2297 changes
=> feat(documentation) - Update TRACES.md

ssvsigner/README.md
Add security notes for SSV-16 and SSV-20
=> [SSV-16,SSV-20] ssvsigner: Possible Local File Read + SSRF via Web3signer_endpoint Configuration

eth/eventsyncer/event_syncer_test.go, eth/executionclient/execution_client.go, eth/executionclient/execution_client_test.go, eth/executionclient/mocks.go, eth/executionclient/multi_client.go, eth/executionclient/multi_client_test.go, operator/duties/scheduler.go, operator/duties/scheduler_mock.go, operator/duties/voluntary_exit.go, operator/duties/voluntary_exit_test.go
Based on: https://github.com/ssvlabs/ssv/pull/1341. 
Reason is mentioned here: https://github.com/ssvlabs/ssv/pull/1341#issuecomment-3032106030
=> [Main] hotfix/refactor: (VoluntaryExit) fetch header instead of block, to get the slot 

doppelganger/README.md, eth/design.md, protocol/v2/qbft/storage/participant_store.go, protocol/v2/ssv/runner/runner_signatures.go
fix some minor issues in comments
=> chore: fix some minor issues in comments
