- .air.toml
- .run/config-remote-debug.run.xml
- Dockerfile.debug
- docker-compose_debug.yaml
@roman-blox  @lior-blox  @alonmuroch - I need your help : ) 
This draft PR is a initial proposal to facilitate contribution to SSV repo by jumping from **git clone** to its **debug** stage.
1 - Setup of [Delve](https://github.com/go-delve/delve) as default debugger for SSV node container.
2 - Setup of [Air](https://github.com/cosmtrek/air) to enable live reload* to Go applications
3 - Setup a ready-to-use **docker-compose** file with **1 debugging node + 2 regular nodes instances.**
*Live Reload was inspired by [this blog post](https://medium.com/easyread/today-i-learned-golang-live-reload-for-development-using-docker-compose-air-ecc688ee076)
it enables the GO app to reload instantaneously after a code change - no need to rebuild the image/container etc
**Docker Compose command to trigger …
> ssv - docker - debug - setup delve debugger and air live reload

- ibft/sync/test_utils.go
- network/local/local.go
- network/network.go
- network/p2p/p2p.go
- validator/validator.go
Resolve https://github.com/bloxapp/ssv/issues/109
Verify topic subscription before setup, in order to avoid error logs when trying to register to a subscribed topic
> check if the node is registered on topic instead of throwing error

- ibft/ibft.go
- ibft/ibft_decided.go
- ibft/ibft_running_instance.go
- ibft/ibft_sync.go
- ibft/instance.go
- ibft/instance_test.go
- validator/duty_execution.go
- validator/test_utils.go
This PR will make the flow validator -> execute duty -> come to consensus -> startInstanceWithOptions -> decided instance one single thread.
This should solve the current instance nilling issues we had + better error handling.
This disables decided msg for current instance handling, will enable later on
> Fix instance loop

- .gitlab-ci.yml
- network/p2p/p2p.go
- network/p2p/p2p_stream.go
Fixing an issue that was found on `ssv-node-v2-1` :
```
738a48d001a3e708540a98975e4f64537f834742d5", "node_id": 4, "role": "ATTESTER"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13aafd6]
goroutine 722 [running]:
github.com/bloxapp/ssv/network/p2p.(p2pNetwork).propagateSignedMsg(0xc0000e4600, 0x0, 0x0, 0x0, 0x0, 0x1)
/go/src/github.com/bloxapp/ssv/network/p2p/p2p.go:260 +0x1d6
github.com/bloxapp/ssv/network/p2p.(p2pNetwork).listen(0xc0000e4600, 0xc00c77bcc0)
/go/src/github.com/bloxapp/ssv/network/p2p/p2p.go:235 +0x6fa
created by github.com/bloxapp/ssv/network/p2p.(p2pNetwork).SubscribeToValidatorNetwork
/go/src/github.com/bloxapp/ssv/network/p2p/p2p.go:202 +0x1ea
make: ** [Makefile:61: start-node] …
```
> Fix nil pointer issue

- beacon/goclient/goclient.go
- cli/operator/node.go
- eth1/goeth/goETH.go
- ibft/change_round.go
- network/p2p/p2p.go
- network/p2p/p2p_decided.go
- network/p2p/p2p_ibft.go
- network/p2p/p2p_signatures.go
- operator/node.go
- validator/controller.go
- validator/storage/storage.go
Improve startup logs to be more readable for users
load validators from config
“operator is setup and fired successfully”  
"Broadcasting to topic" - add topic name in order to distinct between validators
> Readiness log indicator

- .gitlab-ci.yml
- ibft/sync/history.go
- ibft/sync/history_test.go
Resolving sync issues - 
1. **Decided seqNum 0** - 
In case when operator receives remote decided seqNum 0 and local is empty (notFound) we need to save decided 0 and not skip syncing as current happening (what leaving operator not in sync and "stuck")
2. **Handle missing decided** - 
When syncing with peer for range of decided (e.g from 0 to 10) and one of the decided is missing the operator is stuck in infinite loop. this pr handle that case and will raise and error.
**Also added tests for those cases.
> Fix sync issues

- validator/controller.go
- validator/validators_map.go
Coming back to update indices but now it shouldn't be disruptive as before as indices are normally fetched on validator added. In case it was failed for some reason (e.g. validator is not deposited yet) then the index will be updated on the next GetIndices round.
> Restore update indices but keep fetching during sync

- .gitlab-ci.yml
- .k8/yamls/ssv-exporter.yml
- .k8/yamls/ssv-node-v2-1-deployment.yml
- .k8/yamls/ssv-node-v2-2-deployment.yml
- .k8/yamls/ssv-node-v2-3-deployment.yml
- .k8/yamls/ssv-node-v2-4-deployment.yml
- monitoring/README.md
- network/p2p/config.go
- network/p2p/p2p.go
- validator/metrics.go
- validator/validator.go
Following https://github.com/bloxapp/ssv/issues/310, 
This PR adds a pubsub tracer (see [go-libp2p-pubsub#tracing](https://github.com/libp2p/go-libp2p-pubsub#tracing)) which will save the tracing in a local PB file.
The file will be analyzed using [go-libp2p-pubsub-tracer](https://github.com/libp2p/go-libp2p-pubsub-tracer)
Next step -> **remote tracer**
`go-libp2p-pubsub-tracer` includes [traced](https://github.com/libp2p/go-libp2p-pubsub-tracer#traced) to record traces from multiple peers.
By adding that functionality to the exporter node, we can get tracing of the entire network.
> Add pubsub tracing

- ibft/instance.go
- ibft/instance_test.go
- ibft/partial_change_round.go
- ibft/spectesting/tests/change_round_partial_quorum_and_decide.go
- ibft/spectesting/tests/spec_test.go
This solves an issue of bumping round (while f+1 catch up) directly by calling state.round ++ which doesn't execute the necessary bump round logic. 
This caused f+1 to sometimes not execute the change round quorum as it didn't reset:
i.processChangeRoundQuorumOnce = sync.Once{}
i.processPrepareQuorumOnce = sync.Once{}
i.processCommitQuorumOnce = sync.Once{}
> F+1 catch bump round fix

- beacon/types.go
- exporter/api/msg.go
- exporter/node.go
- exporter/query_handlers.go
- exporter/query_handlers_test.go
- exporter/validators_metadata.go
- ibft/sync/history/history_test.go
- ibft/sync/incoming/fetch_decided.go
- ibft/sync/incoming/fetch_decided_test.go
- ibft/sync/test_utils.go
Added WS API for exporting decided messages.
Request filter should include:
* `publicKey` - validator's public key
* `role` - role type
* `from` / `to` - range
```json
{
"type":"decided",
"filter": { 
"publicKey": "80bced0450cfad50f38b856d06c3678e5436f6d29f793e83962b961e21dd7c77b9a94b9ae5a5fa6cc7bd0e7d22abee8f",
"role": "ATTESTER", 
"from":16526,
"to":16527
}
}
```
```json
{
"type": "decided",
"filter": {...},
"data": [
{
"message": {
"type": 3,
"round": 1,
"lambda": "...",
"seq_number": 16526,
"value": "..."
},
"signature": "...",
"signer_ids": [1, 4, 3]
},
{
"message": {
"type": 3,
"round": 1,
"lambda": "...",
"seq_number": 16527,
"value": "..."
},
"signature": "...",
"signer_ids": [2, 1, 4]
}
]
}
```
> Exporter Decided API

- utils/tasks/exec_queue.go
- utils/tasks/exec_queue_test.go
`TestExecQueue` is causing a data race + error (`panic: sync: WaitGroup is reused before previous Wait has returned`)
> Fix unstable test

- exporter/validators_metadata.go
Currently "non-found" validators won't report the status (reported upon metadata response)
> Exporter - report validator status on warmup

- exporter/ibft/commit_reader.go
- exporter/ibft/decided_reader.go
- exporter/ibft/incoming_msgs.go
- ibft/controller/controller_network.go
- ibft/sync/test_utils.go
- monitoring/metrics/health_check.go
- network/local/local.go
- network/local/local_test.go
- network/network.go
- network/p2p/listeners.go
- network/p2p/listeners_test.go
- network/p2p/p2p.go
- network/p2p/p2p_decided.go
- network/p2p/p2p_ibft.go
- network/p2p/p2p_listeners.go
- network/p2p/p2p_pubsub.go
- network/p2p/p2p_signatures.go
- network/p2p/p2p_stream.go
- network/p2p/p2p_sync.go
- network/p2p/p2p_sync_test.go
- network/p2p/p2p_test.go
- validator/validator.go
- improved internal listeners to be de-registered when done
- exporter: add context in waitForMinPeers
- exporter: avoid over-subscription in sync
> Fix internal listeners leak

- ibft/instance/event_loop.go
- ibft/instance/eventqueue/queue.go
- ibft/instance/eventqueue/queue_test.go
- ibft/instance/instance.go
Resolve https://github.com/bloxapp/ssv/issues/434 by wrapping an event/function with a struct to include a cancel function that would be called when the queue will be stopped and drained.
> Event queue leak fix

- exporter/ibft/commit_reader.go
- exporter/ibft/commit_reader_test.go
- exporter/ibft/decided_reader.go
- ibft/controller/controller_decided.go
- ibft/controller/controller_decided_test.go
- ibft/controller/controller_running_instance.go
- ibft/instance/commit.go
- ibft/instance/commit_test.go
- ibft/instance/instance.go
- ibft/instance/instance_test.go
- ibft/instance/spectesting/tests/commit/decide_different_value.go
- ibft/instance/spectesting/tests/common/duplicate_messages.go
- ibft/instance/spectesting/tests/prepare/prepare_at_future_round.go
- ibft/instance/spectesting/tests/valid_simple_run.go
- utils/tasks/exec_timeout_test.go
Resolve https://github.com/bloxapp/ssv/issues/430
IBFT messages were purged once the instance decided or stopped, the behavior changed in this PR:
- when instance finished w/ decided - ctrl starts to listen for late commit messages with timeout and purge messages once done
- when instance finished w/o decided - ctrl purges messages
> Decided message signers fix

- cli/operator/node.go
- operator/duties/controller.go
- operator/duties/controller_test.go
- operator/node.go
Enables to pass a config flag to turn off duty execution in an operator node, means that the node won't take part in validator's consensus
> Read only mode for operator node

- eth1/sync_test.go
- network/commons/listeners/container.go
- network/commons/listeners/container_test.go
- network/commons/listeners/listener.go
- network/p2p/listeners.go
- network/p2p/listeners_test.go
- network/p2p/p2p.go
- network/p2p/p2p_decided.go
- network/p2p/p2p_ibft.go
- network/p2p/p2p_signatures.go
- network/p2p/p2p_stream.go
- network/p2p/p2p_sync.go
- extract listeners from p2p package for reuse and cleaning in general
- added container to manage thread-safe listeners registration, de-registration and invocation
- resolved high memory+goroutines in the previous implementation
> Refactor internal msg listeners

- eth1/goeth/goETH.go
- validator/storage/share.go
- validator/storage/share_opts.go
- validator/storage/share_opts_test.go
- validator/storage/storage_test.go
- validator/utils.go
The purpose of this PR is to handle already exist OwnerAddress field.
in the next ssv-node version`CleanRegistryData` should be enabled by default
https://bloxxx.atlassian.net/browse/BLOXSSV-681
> Validator owner address handling

- exporter/api/broadcaster_test.go
- exporter/api/conn.go
Resolve https://github.com/bloxapp/ssv/issues/484
- Drop messages when the connection does not keep up
> Exporter - avoid sending to non-responsive connections

- beacon/goclient/ekm/signer_storage.go
- exporter/storage/operators.go
- exporter/storage/validators.go
- storage/basedb/storage.go
- storage/kv/badger.go
- storage/kv/badger_test.go
- validator/storage/storage.go
Partially resolve https://github.com/bloxapp/ssv/issues/484
- Read multiple items w/o allocating slice for results
> Optimize get all by collection

- network/p2p/discovery_discv5.go
- network/p2p/op_key_entry.go
- network/p2p/op_key_entry_test.go
- Added implementation of the needed interfaces for an ENR entry (`enr.Entry`, `rlp.Decoder` and `rlp.Encoder`)
- Added `pkh` entry to node's ENR
> Entry for Operator PubKey Hash

- validator/storage/share.go
- validator/storage/share_test.go
- validator/utils.go
- validator/validator.go
- validator/validators_map.go
This PR is a preparation for peers limit change (#487)
- added operators-public-keys collection on share
- values are being hashed once per validator instantiation
**NOTE:** `CleanRegistryData` is required (run once) to align old data
> Operators public keys

- network/p2p/metrics.go
- network/p2p/p2p.go
- network/p2p/peers_index.go
Cleaned some debug logs due to redundancy and overloading.
Some were changed to `trace`, which could be enabled with `NETWORK_TRACE=true`.
> Clean network logs

- exporter/node.go
Avoid starting a validator w/o metadata, as it won't have any operators subscribed to its topic.
The idea is to reduce the amount of topic announcements for irrelevant topics, as it seems to creates massive amount of goroutines due to retries.
> Exporter: skip setup for validator w/o metadata

- network/p2p/conn_handler.go
- network/p2p/metrics.go
- network/p2p/options.go
- updated gossip params:
- `MaxIHaveLength` was set to 2000 (default is 5000) to reduce `IHAVE` floods
- `HistoryLength` was reduced
- updated queue size for validation and outbound queues
- added metrics for streams and connections
> Pubsub config alignment

- .gitlab-ci.yml
- eth1/sync.go
- validator/controller.go
Resolve https://github.com/bloxapp/ssv/issues/461
Move async to sync processing the ETH1 events
on node startup, all events should be scanned and processed before we can start their instance.
> Async to Sync processing ETH1 events

- go.mod
- go.sum
When running node on ARM64 CPU with `github.com/dgraph-io/ristretto@v0.1.0` (used by `github.com/dgraph-io/badger`), the node fails with a `mremap size mismatch` error. 
This was fixed in https://github.com/dgraph-io/ristretto/pull/281. There's no new version of https://github.com/dgraph-io/badger containing the fix, also there's no new release of https://github.com/dgraph-io/ristretto containing the fix. So I'm overriding `github.com/dgraph-io/ristretto`'s version to its latest commit.
> go.mod: override `github.com/dgraph-io/ristretto` version to fix `mremap size mismatch` error

- .gitlab-ci.yml
- ibft/instance/instance.go
> ibft/instance: remove duplicated `node_id` and `pubKey` log fields

- config/example_share.yaml
- dev.Dockerfile
- validator/storage/share.go
- validator/storage/share_opts.go
- validator/storage/share_test.go
After the change of saving all operators needs to check each share if  belong to operator. 
because of this change need to add to local shares the operators field
> allow passing operators to share options

- Dockerfile
Fixes #450 
Fixes #493 
Force using Go's DNS resolver because Alpine's DNS resolver (when `netdns=cgo`) may cause issues.
> Dockerfile: force using Go's DNS resolver on Alpine

- .gitlab-ci.yml
- eth1/sync.go
- migrations/migration_4_clean_exporter_registry_data.go
- migrations/migrations.go
- validator/controller.go
this pr including:
- make the ETH1 history sync to be in synchronic way
- migration to re-sync operators/validators information in exporter
- fix reporting all validator added events to prometheus but only that belongs to operator
> Exporter re-sync indices

- migrations/migration_5_clean_shares.go
- migrations/migrations.go
- validator/controller.go
- add migration to clean registry data
- get metadata only for operator shares
> Empty validator operators hotfix

- network/forks/fork.go
- network/forks/v0/pubsub_mapping.go
- network/forks/v1/pubsub_mapping.go
- network/p2p/p2p.go
- network/p2p/p2p_pubsub.go
- network/p2p/p2p_setup.go
- network/topics/controller.go
- network/topics/controller_test.go
- network/topics/msg_validator.go
- network/topics/msg_validator_test.go
- network/topics/pubsub.go
- network/topics/topic_container.go
This PR introduce the decided subnet, which is a topic for sending decided messages across the network.
In addition, changing topic prefix (`bloxstaking.ssv`) to be included in fork interface.
For fork v1 we'll use `ssv.v1` prefix, future versions will follow the same format (`ssv.<version>`).
The following changes are included:
- register on decided topic upon network start
- send decided messages on decided subnet
> Decided Subnet

- automation/qbft/tests/all_test.go
- network/p2p/p2p_pubsub.go
- network/p2p/p2p_setup.go
- network/topics/msg_validator.go
- operator/validator/controller.go
- protocol/v1/qbft/controller/controller.go
This PR enables nodes to save messages of any validator in the network.
- fixed decided topic:
sending decided messages on decided topic and only after that on the validator topic/s.
- avoid redundant creation of msgID handler
- fix creation of validators instances
> Handle Subnet Validators Post Fork

- network/peers/conn_handler.go
- network/peers/handshaker.go
As part of this PR we silent redundant handshake errors in logs.
The underlying issue is related to bad exchange of user agent by libp2p's `identify` protocol, will be investigated in a later point in time and for now we try to silent these errors as we see good peer count.
- retry identify protocol if user agent was not found
- ignore handshake warning when user agent is not found
> Handshake Error: item not found

- cli/operator/node.go
- network/discovery/dv5_filters.go
- network/discovery/dv5_service.go
- network/discovery/local_service.go
- network/discovery/metrics.go
- network/discovery/service.go
- network/discovery/subnets.go
- network/discovery/subnets_test.go
- network/forks/fork.go
- network/forks/v0/pubsub_cfg.go
- network/forks/v0/pubsub_mapping.go
- network/forks/v1/node_record.go
- network/forks/v1/pubsub_cfg.go
- network/forks/v1/pubsub_mapping.go
- network/forks/v2/node_record.go
- network/forks/v2/pubsub_cfg.go
- network/forks/v2/pubsub_mapping.go
- network/network.go
- network/p2p/config.go
- network/p2p/p2p.go
- network/p2p/p2p_pubsub.go
- network/p2p/p2p_setup.go
- network/peers/handshaker.go
- network/peers/peers_index.go
- network/records/metadata.go
- network/records/node_info.go
- network/records/subnets.go
- network/records/subnets_test.go
- operator/node.go
- operator/validator/controller.go
This PR enables nodes to discover peers based on their subscribed subnets.
- network forks: api to get subnets count and validator subnet
- update subscribed subnets entry (ENR) upon start
- TODO: update entry dynamically / expose discovery interface to be used by pubsub for that purpose
- publish ENR upon subnets change (using pings)
- added discovery metrics
- discover loop: check shared subnets if peers limit reached
- subnets cold start: loaded subnets upon start to ensure we post a (somewhat) updated ENR
> Subnets Discovery

- network/discovery/dv5_service.go
- network/p2p/config.go
- network/p2p/metrics.go
- network/p2p/p2p.go
- network/p2p/p2p_pubsub.go
- network/p2p/p2p_setup.go
- network/topics/controller.go
- network/topics/gossipsub_params.go
- network/topics/pubsub.go
- protocol/v1/sync/changeround/fetcher.go
This PR contains the following changes and fixes:
- increased default max peers to increase message delivery
- modify gossip params to avoid bursts in high load
- increased validation and outbound queues size so messages won't get dropped
- added configs for pubsub params
- logs cleanup
> P2P Fixes and Logs

- monitoring/grafana/dashboard_ssv_operator.json
As part of the forks and v2 changes, the operator dashboard was updated:
- group panels into relevant sections to organize better and avoid performance issues when loading all panels
- added panels for discovery, networking, consensus and other new metrics
This is the first part of a larger epic for grafana dashboards refactoring.
> Grafana: Update Operator Dashboard - Part 1

- network/forks/genesis/pubsub_mapping.go
- network/p2p/config.go
Config alignment for V2:
- modified the default value of following configs so `v2` network won't merge with `v1`:
- `NETWORK_ID`
- `BOOTNODES` (**TODO**)
- changed pubsub topic prefix
> V2 Alignment of Config Defaults

- operator/validator/event_handler.go
The goal of the pr is:
- prevent removing operator and all the shares belongs to it from local db for non-operator nodes, In order to keep the minimum size of the committee.
> Operator removal for non-operator

- protocol/v1/qbft/controller/proccess_message.go
Reducing the number of decided messages that are propagated in the network.
We expect fullnodes to pick up the late commits on their own and therefore the complete decided messages are redundant (we might get 1-3 duplicates).
> Avoid Broadcasting Decided of Late Commit

- .gitlab-ci.yml
- protocol/v1/qbft/controller/controller.go
- protocol/v1/qbft/controller/controller_change_round.go
- protocol/v1/qbft/controller/proccess_message.go
- protocol/v1/qbft/instance/change_round.go
**Current**
Saving change round messages only for non committee.
**New implementation** 
Save change round msg for committee validators. 
Once qbft controller init,  load change round msg’s from storage and add them to the ctrl queue.
**Why?**
Once operator preforming restart (for any reason) we need to check for the local change round msg's and if exist, add them to queue. this action can help the operator to bump to the last round before restarted and eventually speedup change round quorum.
**TBD**
Create SIP.
> Load Change round On startup

- protocol/v1/qbft/instance/change_round.go
- protocol/v1/qbft/instance/change_round_test.go
- protocol/v1/qbft/instance/forks/genesis/fork.go
- protocol/v1/qbft/instance/pre_prepare.go
- protocol/v1/qbft/instance/pre_prepare_test.go
- protocol/v1/qbft/validation/changeround/validate_justification.go
- protocol/v1/qbft/validation/preprepare/validate.go
- protocol/v1/qbft/validation/preprepare/validate_test.go
- protocol/v1/qbft/validation/signedmsg/quorum.go
- spectest/qbft/qbft_mapping_test.go
Depends on https://github.com/bloxapp/ssv/pull/679 and branch `align-error-messages` of `ssv-spec`
Fixes:
- proposal.JustificationsNotHeighest()
- proposal.JustificationsValueNotJustified()
- proposal.DuplicateMsg()
- proposal.FutureRoundNoAcceptedProposal()
- proposal.FutureRoundAcceptedProposal()
- proposal.PastRound()
- proposal.InvalidRoundChangeJustificationPrepared()   
- proposal.InvalidRoundChangeJustification()           
- proposal.PreparedPreviouslyNoRCJustificationQuorum() 
- proposal.NoRCJustification()  
- proposal.PreparedPreviouslyNoPrepareJustificationQuorum() 
- proposal.PreparedPreviouslyDuplicatePrepareMsg()         
- proposal.PreparedPreviouslyDuplicateRCMsg()            
- proposal.DuplicateRCMsg()                           
- …
> Align qbft proposal message processing with spec

- protocol/v1/qbft/instance/change_round.go
- protocol/v1/qbft/instance/change_round_test.go
- protocol/v1/qbft/instance/commit.go
- protocol/v1/qbft/instance/forks/genesis/fork.go
- protocol/v1/qbft/instance/instance.go
- protocol/v1/qbft/instance/pre_prepare.go
- protocol/v1/qbft/instance/pre_prepare_test.go
- protocol/v1/qbft/instance/prepare.go
- protocol/v1/qbft/instance/prepare_test.go
- protocol/v1/qbft/validation/changeround/validate_justification.go
- protocol/v1/qbft/validation/changeround/validate_justification_test.go
- protocol/v1/qbft/validation/commit/validate.go
- protocol/v1/qbft/validation/commit/validate_test.go
- protocol/v1/qbft/validation/prepare/validate.go
- protocol/v1/qbft/validation/prepare/validate_test.go
- protocol/v1/qbft/validation/preprepare/validate.go
- protocol/v1/qbft/validation/preprepare/validate_test.go
- protocol/v1/qbft/validation/signedmsg/msg_round.go
- protocol/v1/qbft/validation/signedmsg/proposal.go
- protocol/v1/qbft/validation/signedmsg/proposal_test.go
- protocol/v1/qbft/validation/signedmsg/quorum.go
- spectest/qbft/qbft_mapping_test.go
Depends on https://github.com/bloxapp/ssv/pull/671 and branch `align-error-messages` of `ssv-spec`
Fixes:
- prepare.MultiSigner()
- prepare.NoPreviousProposal()
- prepare.OldRound()
- prepare.FutureRound()
- prepare.WrongData()
> Align qbft prepare message processing with spec

- network/peers/connections/handshaker.go
changed warning to debug log in case we filter a peer (e.g. peer from another network)
> Reduce handshake logs

- network/forks/genesis/sync.go
- network/p2p/p2p_setup.go
- network/p2p/p2p_sync.go
- network/p2p/p2p_test.go
- protocol/v1/sync/handlers/decided_history.go
- protocol/v1/sync/handlers/last_change_round.go
- protocol/v1/sync/handlers/last_decided.go
This PR contains several enhancements and fixes to the sync components, specifically change round scenario:
* increased the number of peers for syncing change round (`5` to `10`)
* shuffle peers for all sync requests (so we'll get a different set of nodes in every request)
* filter duplicated messages for all stream protocols to avoid redundant processing
* added test for syncing change round
> Change Round Fixes

- migrations/migration_7_clean_operator_removals_corruptions.go
- migrations/migrations.go
A followup commit for #720
Will enforce cleanup of corrupted data
> Migration 7: clean operator removals corruptions

- protocol/v1/qbft/controller/msgqueue_consumer.go
Fixing panic that was caused as we didn't nil-checked the right reference of `currentInstance`
> Fix Nil Pointer Dereference

- protocol/v1/qbft/msgqueue/queue.go
Fix for the following issue:
```
fatal error: concurrent map iteration and map write
goroutine 291196 [running]:
runtime.throw({0x19d8450, 0xc015634010})
/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc020bcfb60 sp=0xc020bcfb30 pc=0x439fd1
runtime.mapiternext(0x1869148)
/usr/local/go/src/runtime/map.go:858 +0x4eb fp=0xc020bcfbd0 sp=0xc020bcfb60 pc=0x412a6b
github.com/bloxapp/ssv/protocol/v1/qbft/msgqueue.(*queue).WithIterator(0xc0101c7710, 0xc, 0x1, 0xc010c58ae0)
/go/src/github.com/bloxapp/ssv/protocol/v1/qbft/msgqueue/queue.go:190 +0x99 fp=0xc020bcfcd8 sp=0xc020bcfbd0 pc=0xe32fb9
github.com/bloxapp/ssv/protocol/v1/qbft/controller.(*Controller).processHigherHeight(0xc001b93860, 0xc0057df540, {0xc000195650, 0x68}, 0x1988, 0xc00753a6a0) …
```
> Fix qbft msgqueue concurrent map iteration and map write panic

- protocol/v1/qbft/types.go
`RoundStateName` doesn't include `RoundStateReady`, so round names are off by one in logs, e.g. `RoundStateChangeRound` has a value `5` and is shown as `Decided`.
> Fix round state names

- protocol/v1/p2p/min_peers.go
Node has a 500ms delay on every duty execution. The PR changes the behavior by waiting only if there are not enough peers or if peers cannot be checked.
> Avoid delay on every check for peers

- ibft/storage/stores.go
- network/p2p/p2p_pubsub.go
- network/p2p/p2p_sync.go
- network/topics/controller.go
- network/topics/topic_container.go
- operator/node.go
- protocol/v2/qbft/instance/instance.go
- protocol/v2/ssv/spectest/ssv_mapping_test.go
- protocol/v2/ssv/spectest/utils/storage.go
By delegating concurrency to the p2p layer.
- broadcast: use goroutines and apply limit in topic container
- use goroutines for sync
In addition, commenting out some failing test cases in `ssv` package (**TODO**)
> Fix data races in spectests

- Makefile
- tests.Dockerfile
- added make cmd `docker-spec-test`
- changed `test.Dockerfile` to be called with any cmd
> Make: spec test in docker

- network/discovery/dv5_service.go
- network/p2p/p2p_setup.go
- network/p2p/p2p_sync.go
- network/p2p/p2p_test.go
- network/p2p/test_utils.go
- network/peers/connections/conn_handler.go
- network/peers/connections/handshaker.go
- network/streams/controller.go
Fixing some issues with libp2p streams, that lead to disconnections and multiple warning logs.
- remove pending cache for handshake 
(caused deadlines in case of multiple handshake attempts)
- logs alignment
- added resource manager to apply stream limits (TODO: check in scale)
see [libp2p: dos mitigation](https://docs.libp2p.io/concepts/security/dos-mitigation/#leverage-the-resource-manager-to-limit-resource-usage-go-libp2p-only)
> Streams Deadline

- .gitlab-ci.yml
- Dockerfile
After #835 which caches `go build`, this PR adds cache for `go mod download` 💪
> Keep Go mod cache across Docker builds (superfast builds: part 2)

- protocol/v2/blockchain/beacon/validator_metadata.go
- utils/tasks/exec_timeout.go
change `logex.GetLogger(("who", "xxx"))` to `logex.GetLogger().Named("xxx")`
> removing "who" tags from logex.GetLogger()

- storage/kv/badger.go
Fix the occasional panic in badger by always providing a non nil logger
> Fix badger panic

- monitoring/grafana/dashboard_ssv_node.json
- monitoring/grafana/dashboard_ssv_operator_performance.json
- sometimes there are issues with no data when a 2m data interval is chosen. It seems 5m works better
- 15m time range is changed to 6h for convenience
> Fix Grafana dashboard intervals

- protocol/v2/ssv/validator/msgqueue_consumer.go
removing duplicated role fields from
`❗ could not handle message`
> `role` duplication fix

- logging/fields/fields.go
- operator/duties/fetcher.go
- protocol/v2/ssv/validator/validator.go
This PR replaces the huge JSON array in the `got duties` log with a small list of duty IDs.
> Log duty IDs instead of JSON

- network/peers/conn_manager.go
- operator/validator/controller.go
- protocol/v2/ssv/runner/attester.go
- protocol/v2/ssv/runner/proposer.go
- protocol/v2/ssv/runner/sync_committee.go
Operators should see whether they're submitting attestations or not without enabling DEBUG level.
> Level Beacon submission logs up to INFO

- cli/bootnode/boot_node.go
- cli/config/config.go
- cli/export_keys_from_mnemonic.go
- cli/generate_operator_keys.go
- cli/operator/node.go
- cli/threshold.go
- config/config.example.yaml
- go.mod
- go.sum
- integration/qbft/tests/setup_test.go
- logging/global.go
- logging/testing.go
rotate log files using `lumberjack`. send all debug logs into a file in json format.
This PR adds functionality that lets you write structured logs ( json formatted logs { "L": level, "M": msg, "T": time, "field": field}.
This way indexing services like Elastic can easily index these lines and give us nice features in Kibana or KQL to search the logs.
note about log file rotation
currently I added in-code log file rotation using lumberjack lib, the best practice is that the env will take care of it and our app won't be concerned with compressing and moving files. this is temporary so we won't explode our cloud nodes with endless logs.
we'll need to do some research and consult @zevzek and come with a better rotation solution.
> ship logs into a file and stdout at the same time.

- integration/qbft/tests/scenario_test.go
- operator/duties/controller.go
This PR removes useless CGO calls to deserialize & serialize public keys in `ExecuteDuty`.
> `ExecuteDuty` Without CGO

- cli/operator/node.go
- network/p2p/config.go
- network/p2p/p2p_setup.go
- network/p2p/test_utils.go
- network/peers/connections/handshaker.go
- network/peers/connections/handshaker_test.go
- network/peers/connections/helpers_test.go
The permissioned feature previously only checked for the slot in the startup of the node. we want to enable nodes to change accordingly during operation hence this change.
> Hotfix permissioned rollout

- .gitlab-ci.yml
- .k8/scripts/deploy-ssv-node-v3-yamls-on-stage-k8s.sh
- ekm/eth_key_manager_signer.go
- go.mod
- go.sum
- logging/fields/fields.go
- operator/validator/controller.go
- protocol/v2/message/msg.go
- protocol/v2/qbft/instance/instance.go
- protocol/v2/qbft/instance/round_change.go
- protocol/v2/qbft/testing_utils.go
- protocol/v2/ssv/queue/message_prioritizer_test.go
- protocol/v2/ssv/queue/messages.go
- protocol/v2/ssv/queue/queue.go
- protocol/v2/ssv/queue/queue_test.go
- protocol/v2/ssv/runner/attester.go
- protocol/v2/ssv/runner/proposer.go
- protocol/v2/ssv/runner/runner.go
- protocol/v2/ssv/runner/runner_state_helpers.go
- protocol/v2/ssv/runner/validator_registration.go
- protocol/v2/ssv/spectest/ssv_mapping_test.go
- protocol/v2/ssv/testing/runner.go
- protocol/v2/ssv/validator/msgqueue_consumer.go
- protocol/v2/ssv/validator/validator.go
- protocol/v2/testing/test_utils.go
- protocol/v2/types/crypto.go
Sometimes messages are being processed prematurely which leads to them being rejected, for example:
1. Prepares/commits for a proposal that wasn't yet received
2. Proposal for a duty that wasn't yet started
This PR refactors `priorityQueue` to support popping messages with a filter, and uses this new ability to avoid popping certain messages too early, specifically:
1. **If no duty is running, pop only ExecuteDuty messages**
*This keeps pre-consensus/consensus messages in the queue, until we're ready to process them.*
2. **If no proposal was accepted for the current round, skip prepare & commit messages for the current height and round**
*This helps handle network-layer asynchrony. While prepares & commits are sent after proposals, they're sometimes received before.*
> Conditional Popping

- operator/validator/controller.go
We had a panic happen at stage env that was a result of `ValidatorRemoved` event that was fired during 
`UpdateValidatorMetadata` this resulted in the validator not being in the `validatorMap` and yet we tried to activate it using a share from the DB, which wasn't returning an error but did return an empty share (nil) which panicked when we tried to use (log it in this case)
on `UpdateValidatorMetadata` a new check on `Share` will make sure we wont start the share if it is empty.
We should revamp this area, to make sure validator events are interlocked with routinely updating the validator metadata. This will probably happen as part of a bigger change in the way we receive, handle and store all the information from ETH1 node.
> Validator metadata panic

- protocol/v2/ssv/validator/events.go
Return errors returned by `OnTimeout` and `OnExecuteDuty` instead of just logging them
> [Audit Issue E] Handle event message processing errors

- network/syncing/syncer_test.go
Log duration in `TestThrottle`, it might be helpful because this test is flaky locally
> Log duration in TestThrottle

- .gitlab-ci.yml
- eth1/goeth/goETH.go
- network/p2p/p2p.go
This PR fixes a case where `p2pNetwork.Subscribe` is being called in runtime as new validators join, but the subnets record isn't updated neither in the node's metadata and the new topics aren't being registered to.
This is a temporary PR until https://github.com/bloxapp/ssv/pull/990 for until is ready.
> Fix Runtime Subscriptions

- protocol/v2/qbft/instance/compact.go
- protocol/v2/qbft/instance/compact_test.go
`copy` is a builtin and should not be shadowed
> Fix builtin shadowing

- network/syncing/syncer.go
- protocol/v2/qbft/spectest/controller_type.go
- protocol/v2/ssv/queue/messages.go
- protocol/v2/ssv/runner/runner.go
- protocol/v2/ssv/spectest/multi_start_new_runner_duty_type.go
Some imports are duplicated, e.g.:
```go
"github.com/bloxapp/ssv-spec/qbft"
specqbft "github.com/bloxapp/ssv-spec/qbft"
```
> Remove duplicated imports

- cli/operator/node.go
- eth1/goeth/goETH.go
- monitoring/metrics/handler.go
- network/p2p/p2p_setup.go
- If metrics server cannot be started, it likely means a configuration error which should not be hidden
- If streaming smart contract events fails, then `listenToSubscription` doesn't happen anymore, which means it's better to restart and try again. Probably we could add some code to handle this case instead.
- If `n.cfg.Subnets` cannot be parsed, then config is malformed, and crashing would show this
> eth1/goeth, monitoring/metrics, network/p2p: crash if setup fails

- .gitlab-ci.yml
- monitoring/metrics/handler.go
Ever since #991 we can't request pprof profiles fora duration >3 seconds. This PR increases the timeout.
> chore: increase timeout to allow for long-running pprof requests

- operator/fee_recipient/controller_test.go
- operator/validator/controller.go
- operator/validator/event_handler.go
- registry/storage/shares.go
- registry/storage/shares_test.go
This PR primarily improves the integrity of the in-memory replica.
- Update database first in `Save` & `Delete` (to prevent updating in-memory if database update failed)
- Remove `logger` parameter from `Save` because it isn't needed anymore
> Share Caching Patches

- api/handlers/validators.go
- operator/validator/controller.go
- Respond with the validator's status, index and Eth1 owner address in `/v1/validators`
- Exporter nodes now fetch metadata for all validators so they can provide their statuses & indices
> feat: (api) provide status, index and owner address at `/v1/validators`

- eth/eventhandler/handlers.go
- network/p2p/p2p_test.go
This PR fixes a bug where operators wouldn't bump the owner's nonce when the share belongs to them and is not encrypted correctly.
NOTE: the other operators (who couldn't verify the encryption) will still save the share to their database, so there will be a discrepancy between the owning operator and the others.
> fix: (`handleValidatorAdded`) bump nonce on share decryption error

- protocol/v2/types/ssvshare.go
- registry/storage/shares_test.go
Max share size seems to be 1245. Limiting max allowed input size to twice of that
> [Audit Issue C] Limit decoded share size

- ekm/eth_key_manager_signer.go
- ekm/signer_key_manager_test.go
- network/peers/subnets.go
This PR adds various slashing tests which attempt to prove that the slashing protection would block double & surrounding votes.
> test: add slashing tests

- cli/cli.go
- cli/operator/generate_doc.go
- docs/configuration.md
This PR adds a CLI command to automatically generate documentation about the available YAML/env options.
Example output:
```
┌─────────────────────────────────────────────────┬──────────────────────────────┬──────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                      YAML                       │             ENV              │     Default      │                                             Description                                             │
├─────────────────────────────────────────────────┼──────────────────────────────┼──────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ global                                          │ …
```
> Configuration Docs

- operator/duties/scheduler_test.go
- operator/duties/validatorregistration.go
One of the subscribers of that channel was not reading messages from it, which caused the `event.Feed` to get stuck on it's `Send` method for eternity.
> fix: jammed `indicesChange` channel

- ekm/eth_key_manager_signer.go
- ekm/signer_storage.go
- eth/eventhandler/event_handler.go
- eth/eventhandler/event_handler_test.go
- eth/eventhandler/handlers.go
- eth/eventhandler/task.go
- eth/eventhandler/task_executor_test.go
- logging/fields/fields.go
- operator/validator/controller.go
- operator/validator/mocks/controller.go
- operator/validator/task_executor.go
Previously, shares were being removed based on the validator's public key, which was incorrect.
This fix introduces the proper way to delete a share by using the share's public key instead of the validator's public key. This ensures that the correct share is removed from the EKM (ETH Key Manager) storage.
UPD: based on @moshe-blox [comment](https://github.com/bloxapp/ssv/pull/1140#pullrequestreview-1618840674)
added a logic that interact with database to be as part of the tx in eventhandler.
> Fix: Use Share PublicKey for Share Removal

- ekm/eth_key_manager_signer.go
- ekm/signer_key_manager_test.go
- eth/eventhandler/event_handler_test.go
- eth/eventhandler/handlers.go
- eth/eventhandler/local_events_test.go
- eth/eventhandler/task_executor_test.go
- utils/testutils.go
This PR addresses the issue of outdated slashing protection data for reactivated validators in the EKM (Ethereum Key Manager). Specifically, it aims to prevent the signing of slashable attestations or proposals by ensuring that the slashing protection data is updated appropriately when a validator is reactivated.
- Added logic to update slashing protection data for reactivated validators.
- The slashing protection data is "bumped" to the next epoch & slot only if the stored values are lower. This ensures that we do not overwrite higher stored values.
```go
storedEpoch = max(nextEpoch, storedEpoch)
```
- Added unit tests to verify that the slashing protection data is updated correctly.
> Implement Slashing Protection Data Update for Reactivated Validators

- api/handlers/node.go
- api/handling.go
- api/server/server.go
- Fix `api.Render` — other routes were panicing because default content type of browser request is text/plain, but they didn't return a string.
- For text/plain requests, encode indented JSON instead of fmt.Printf (looks nearly the same, but more maintainable than custom format)
- Extract special fields to "advanced" struct
Example response:
```json
{
"p2p": "bad: no peers are connected",
"beacon_node": "good",
"execution_node": "good",
"event_syncer": "good",
"advanced": {
"peers": 0,
"inbound_conns": 0,
"outbound_conns": 0,
"p2p_listen_addresses": [
"192.168.1.112:13001"
]
}
}
```
> refactor: node health API

- api/handlers/node.go
- cli/operator/node.go
we were using libp2p to get the addresses to show in the health route, while this works in K8S, local node will publish their local IP, so now we are passing in the host address and advertising it.
found with @moshe-blox
> Fix: health route host addres

- .dockerignore
- Dockerfile
- Makefile
- cmd/ssvnode/main.go
I don't know why we had ignored `.git`. so unless we have a good reason, I suggest including it in order to be able to get git info.
the alternative is to generate this and pass to the docker build command from outside.
> Include git commit/version in Docker build

- ekm/signer_key_manager_test.go
Implement slashing tests according to the conditions presented in https://github.com/protolambda/eth2-surround#problem
and requested by audit
> Missing Slashing Tests

- cli/operator/node.go
- go.mod
- go.sum
- operator/slotticker/slotticker.go
- operator/slotticker/slotticker_test.go
- operator/slotticker/timer.go
This PR fixes a bug where the SlotTicker wakes up earlier than planned, for example 11.999 seconds into the same slot it already ticked on, and ends up ticking the same slot again.
See https://github.com/bloxapp/ssv/pull/1244#discussion_r1431331559 for more explanation.
> fix: (SlotTicker) potential double tick

- .gitlab-ci.yml
- beacon/goclient/goclient.go
Prysm v4.2.1 fixed the incorrect endpoint which we depended on in `checkPrysmDebugEndpoints` (they reverted it back to the correct `v1` path).
For that reason, we're now querying a different debug endpoint which didn't change in order to support both Prysm v4.2.0 and v4.2.1
> fix: switch endpoint in `checkPrysmDebugEndpoints`

- operator/duties/attester_test.go
- operator/duties/mocks/scheduler.go
- operator/duties/proposer.go
- operator/duties/proposer_test.go
- operator/duties/scheduler.go
- operator/duties/sync_committee.go
- operator/duties/sync_committee_test.go
- operator/validator/controller.go
- operator/validator/controller_test.go
This PR makes `AllActiveIndices` (optionally) wait for a channel that is closed only when an initial validators setup has already happened.
It aims to solve a situation where an operator that asked for sync-committee duties before validators setup will think it does not have any validators with sync-committee duties for a whole period, resulting in a lot of missing sync committee duties.
made with @moshe-blox
> fix: get own sync committee duties after validators setup.

- protocol/v2/ssv/runner/proposer.go
This PR covers the case of `BlockContents` in `summarizeBlock`, which was missing in the Deneb upgrades.
> fix: (ProposerRunner) missing block summary for Deneb

- Dockerfile
The version `20230506-r0` causes build failures. 
The new version `20240226-r0` is taken from https://pkgs.alpinelinux.org/packages?name=ca-certificates&branch=edge&repo=&arch=&maintainer=
> Update ca-certificates version

- Dockerfile
- operator/keys/jemalloc_check.go
- operator/keys/keys.go
- operator/keys/rsa.go
- operator/keys/rsa_linux.go
- operator/keys/rsa_linux_test.go
This uses  is based on #1274 and uses parts from #1348.
- When running linux use https://github.com/microsoft/go-crypto-openssl/ which is orders of magnitude faster than golang std lib.
- docker to run from ubuntu golang to have openssl by default
- disable jemalloc because it clashes with openssl and causes panic (check the build and panic if jemalloc is present)
>  optimization: use miscrosoft/openssl for RSA sign/verify

- network/topics/params/topic_score.go
The PR adjusts the pubsub scoring calculation algorithm by multiplying `msgsPerValidatorPerSecond` by `clusterConsensusReductionFactor` (0.15)
> Adjust pubsub scoring calculation

- operator/duties/validatorregistration.go
Our duty ids for validators registrations we're missing the validator index hence all of them were being printed like this :
`VALIDATOR_REGISTRATION-e32454-s1038539-v0` for all validators. 
This PR adds the validator index to the Duty passed from the validator registration scheduler so the duty format func will put in a validator index.
*NOTE*: This PR has no effect on consensus as the validator registration duty runner isn't signing or using the full duty struct for anything.
> fix: add validator index in validator registration duty id

- Dockerfile
In our Makefile we are setting HOST_ADDRESS env to pass to the node in order to advertise itself in discovery. when we introduced #1358 , we switched to using a different image in docker and this image lacks `dig` which is the utility we use to resolve our address against a dns service.
this installs dnsutils which has dig so we could get our address.
> fix: find host address using dig

- operator/duties/committee.go
- registry/storage/shares.go
This change resolves issue when new validator are registered and index in spectypes share is not updated from metadata.
> fix validator index in spec share

- message/validation/consensus_validation.go
- message/validation/errors.go
When a validator is registered while in a sync committee, the other operators would not fetch their duties on time.
This bug causes network instability, resulting in reduced attestation rate for the registered validator and their operators.
This PR reduces the impacts of this bug down to at maximum one validator.
> fix: (MessageValidation) ignore missing sync duties

- network/p2p/p2p_setup.go
- network/peers/connections/handshaker.go
Fake version should be unnecessary given domain type has changed and peers with mismatching domain type should be rejected anyway.
> remove fake Alan version

- message/validation/common_checks.go
- message/validation/consensus_state.go
- message/validation/consensus_state_test.go
- message/validation/consensus_validation.go
- message/validation/partial_validation.go
- message/validation/signer_state.go
- message/validation/validation.go
- message/validation/validation_test.go
The PR adds the new `OperatorState` structure, it has some logic, so we need to consider covering it with unit tests
> message validation: replace treemap with an array

- protocol/v2/ssv/validator/committee.go
We were copying all shares when only the shares that are relevant for this slot duty should go into the runner.
> fix: pass only relevant duty validator shares into the slot committee runner

- eth/eventhandler/handlers.go
- operator/duties/attester.go
- operator/duties/committee.go
- operator/duties/proposer.go
- operator/duties/sync_committee.go
- operator/duties/validatorregistration.go
- operator/duties/voluntary_exit.go
- operator/validator/controller.go
- operator/validator/controller_test.go
- operator/validator/mocks/controller.go
- protocol/v2/types/ssvshare.go
- registry/storage/shares.go
port of https://github.com/ssvlabs/ssv/pull/1429
> refetch duties after metadata update

- operator/validator/controller.go
A bug that managed to get through the CR process, was stopping handling messages in exporter if it received a message that wasn't consensus or partial sig. (could be EventMsg like Timeout or ExecuteDuty).
`continue` instead of `return`
> fix: (alan) don't return on unhandled message types in exporter

- operator/validator/controller.go
- protocol/v2/ssv/validator/committee.go
On `validator/controller.go` we were creating the functions to start a new `committeeRunner`, like before every runner uses a value check to make sure its running consensus on valid and non slashable value. We commented this part out and used our own version that doesn't use slashing check, this was because value check are usually implemented in the spec and the spec wasn't ready when this code was written.
Now that the spec is ready, the code is aligned to use the `beaconVoteValCheck` from the spec which includes a value check for all the provided shares.
> fix: (alan) bring back slashing check from spec

- protocol/v2/ssv/runner/committee.go
We saw a few cases where a response from the beacon node indicated an empty message sent.
Don't submit if there is no data to send.
> fix: (alan) don't submit empty attestation or sc messages

- network/topics/pubsub.go
- network/topics/scoring.go
This PR improves the p2p scoring log. Namely, it adds the explicit counters for p1, p2, p4, p6 and p7.
In the `network/topics/pubsub.go:NewPubSub` function, the order of some initialization calls was changed so that `scoreInspector` could access topics' parameters and overall score parameters.
> Improve p2p scoring log

- message/validation/consensus_validation.go
- message/validation/const.go
- message/validation/errors.go
- message/validation/genesis/consensus_validation.go
- message/validation/genesis/errors.go
- message/validation/genesis/message_counts.go
- message/validation/genesis/partial_validation.go
- message/validation/genesis/signer_state.go
- message/validation/genesis/validation.go
- message/validation/genesis/validation_test.go
- message/validation/partial_validation.go
- message/validation/validation.go
- message/validation/validation_test.go
This PR applies the suggestions of the message validation review: https://github.com/ssvlabs/ssv/pull/1482
- Update the "validator index match ValidatorPK or CommitteeID" rule to be checked only for validator duties.
- Add the `ProposalMsgType` check before updating `ProposalData` in the state.
- Add slot time and beacon duty checks in PartialSignatureMessages validation.
- Fix > to >= in `MessageCount`.
- Add assertion and `ErrNoSigners` error in `MessageCount` for completeness.
- Add default check for a wrong message type in `ValidateSSVMessage`.
> Fix message validation (review)

- .gitignore
- scripts/differ/transformers.go
- scripts/differ/transformers_test.go
Apparently a regex using `\b` is unsafe in some scenarios. We've seen it match and therefore replace more than just package names.
This PR refactors the regex to match package names more precisely and thus safely.
> fix: (differ) bug in package name reduction

- registry/storage/shares.go
- registry/storage/validatorstore.go
- registry/storage/validatorstore_test.go
This PR optimizes the share saving mechanism by:
1. Updating ValidatorStore in bulks
2. Reduce runtime complexity of ValidatorStore.handleSharesUpdated significantly (up to 100x faster)
Benchmark included.
> optimization: (ValidatorStore) share updates

- operator/duties/proposer_test.go
Tests were broken by last PR to stage, actually they were not correct as they were running pre-fork epoch but expecting post-fork duties. hence the bug we had. this fixes the tests.
we should now add genesis proposal tests as well as mentioned here https://github.com/ssvlabs/ssv/issues/1607
> fix proposer test by fixing them to post-fork

- eth/eventhandler/event_handler_test.go
- eth/executionclient/execution_client_test.go
Passing *testing.T to logger in `eventhandler` tests is a problem, due we have goroutines spawned inside the tested main logic which use the same logger instance even after the test is finished.
Let's use `zap.NewDevelopment()` instead of `zaptest.NewLogger(t)` at least for tests where we call `StreamLogs()` to prevent flaky panics and data races in unit tests. 
Closes https://github.com/ssvlabs/ssv/issues/1585
> Fix EventHandler flaky tests 

- .golangci.yaml
After `golangci-lint` update to `1.60.2` with go `v1.23.0` we have a problem with type casts to `int`. The new rule of `gosec` linter -- `G115` Int overflow breaks our Lint pipeline. Even this rule is pretty useful, it's hard to fix all of the issues.
> chore: (lint) temporarily exclude G115 rule

- message/validation/message_counts.go
This PR adds a small fix to a `MessageCounts` check: a `>` comparison should rather be `>=`.
This caused no issues before since only one extra message was allowed.
> fix: (validation) MessageCounts check

- network/discovery/dv5_routing.go
- network/discovery/dv5_service.go
- network/discovery/dv5_service_test.go
- network/discovery/local_service.go
- network/discovery/service.go
- network/p2p/p2p.go
- network/p2p/p2p_setup.go
- networkconfig/holesky-stage.go
**Changes**
- Fix domain type check
- Reduce discovery interval to match `main`
- Publish ENR only once after adding/removing subnets
- Switch to bootnode hosted on stage
> fix: (discovery) incorrect domain type check and stale ENR on fork

- protocol/genesis/qbft/instance/prepare.go
- protocol/genesis/qbft/instance/proposal.go
- protocol/v2/qbft/instance/prepare.go
- protocol/v2/qbft/instance/proposal.go
Replace hyphens in logs with underscore to prevent issues.
> refactor: hyphens to underscores

- protocol/genesis/ssv/genesisqueue/queue.go
- protocol/genesis/ssv/genesisqueue/queue_test.go
- protocol/v2/ssv/queue/queue.go
- protocol/v2/ssv/queue/queue_test.go
There is currently bug in queue that returns nil even though queue has more msg inside.
So basic flow is:
- we receive msgA into the queue that's not matching filter
- we now receive another one msgB that's will match the filer
- after breaking from main loop in `Pop` we read msg again
- we get again non filter matching one msgC
- in `pop` if msgB is true on filter but doesn't have prio over msgC we will return nil
There is test simulating this scenario
> fix: (queue) nil return condition in Pop

- logging/fields/fields.go
- message/validation/errors.go
- message/validation/logger_fields.go
- operator/validator/controller.go
- protocol/genesis/ssv/validator/validator.go
- protocol/v2/ssv/validator/committee.go
- protocol/v2/ssv/validator/duty_executer.go
- protocol/v2/ssv/validator/validator.go
- protocol/v2/types/operator.go
In debugging we a missed duty we use DutyID as a way to look on all logs related to this duty, we know that sometimes messages are dropped in the P2P layer but currently its not easy to connect the consensus process messages to the p2p layer logs about rejecting/ignoring messages.
This change adds a duty ID field to msg validation logs about ignores/rejects, it checks whether the logger is on debug level to do so, since to make up the duty id, a call to validatorStore is required and we want to prevent it if not necessary.
> logs: (alan) add dutyID to msg validation ignore/rejects

- protocol/v2/ssv/validator/committee_queue.go
#1674 introduced a bug where we didn't grab consensus messages until it was decided, hence we never decided.
> fix: queue priority not take partial messags until decided

- go.mod
- go.sum
- ibft/genesisstorage/stores.go
- ibft/storage/stores.go
- message/validation/genesis/consensus_state.go
- message/validation/genesis/validation.go
- network/p2p/p2p.go
- network/p2p/p2p_pubsub.go
- network/p2p/p2p_validation_test.go
- network/topics/sub_filter.go
- operator/duties/attester_genesis_test.go
- operator/duties/attester_test.go
- operator/duties/committee_test.go
- operator/duties/proposer_genesis_test.go
- operator/duties/proposer_test.go
- operator/duties/sync_committee_genesis_test.go
- operator/duties/sync_committee_test.go
- operator/slotticker/slotticker_test.go
- protocol/genesis/ssv/validator/validator.go
- protocol/v2/ssv/validator/signature_verifier.go
- protocol/v2/ssv/validator/validator.go
- utils/hashmap/hashmap.go
- utils/hashmap/hashmap_test.go
As we found that `cornelk/hashmap` has a bug where it would sometimes silently fail store one of the entries, it was decided just to use regular `sync.Map` as our `hashmap` package backend.
> fix: replace `cornelk/hashmap` with `sync.Map`

- logging/fields/fields.go
- message/validation/logger_fields.go
- protocol/genesis/ssv/validator/validator.go
- protocol/v2/ssv/validator/validator.go
#1653 introduced a logging bug where duties in the `duties` field are formatted using the runner role, means they all get "COMITTTEE" when they are committee duties. We want to support any duty role type so a string might fix better this parameter to enable flexibility.
> fix: duties log string for committee duties

- network/p2p/p2p_setup.go
- network/topics/controller_test.go
- network/topics/msg_id.go
We noticed an issue where `main` and pre-fork - `stage` were tagging each other as `low_score` peers, reducing each other peers because they sent each other `selfOrigin` message, which is an internal mechanism in `go-libp2p-pubsub` to reduce score based on peers that are sending us our own messages.
We were puzzled by this for a while because the `go-libp2p` `Publish` func has a mechanism in place to stop this -
```go
out := rpcWithMessages(msg.Message)
for pid := range tosend {
if pid == from || pid == peer.ID(msg.GetFrom()) { // this should skip original sender of the message
continue
}
gs.sendRPC(pid, out)
}
```
Apparently these messages were arriving from the heartbeat of control message libp2p uses to fill the "gaps" of messages, using an anti-entropy mechanism where they publish …
> fix (alan): use genesis func to generate msgid on pre-fork

- message/validation/logger_fields.go
If `validateSignedSSVMessage` returns an error, then `SSVMessage` is not set: https://github.com/ssvlabs/ssv/blob/b30bc8b4ed4ebf862ebc16f924c11239619c0c63/message/validation/validation.go#L128. 
In this case, `buildLoggerFields` panics in https://github.com/ssvlabs/ssv/blob/b30bc8b4ed4ebf862ebc16f924c11239619c0c63/message/validation/logger_fields.go#L64 on `decodedMessage.GetID()` because it's actually `decodedMessage.SSVMessage.GetID()` since `SSVMessage` is embedded into `queue.SSVMessage`.
The PR adds a check if `decodedMessage.SSVMessage` is `nil` and changes usage like `decodedMessage.GetID()` to `decodedMessage.SSVMessage.GetID()` for clarity.
> message validation: fix panic on malformed SignedSSVMessage

- message/validation/consensus_validation.go
- message/validation/const.go
- message/validation/partial_validation.go
When the attack simulator sends a partial signature message with a payload of 1000 messages, such message gets rejected with the error `ssv message data too big, got 144020, want 144016` because max messages sizes of consensus and partial signature messages don't count encoding overhead (we only count overhead of signed message)
The PR allows 5% encoding overhead for all encoded messages. It may be easily adjustable by changing `encodingOverheadDivisor`
> fix: (validation) consider encoding overhead in max consensus & partial signature message sizes

- eth/eventhandler/event_handler_test.go
- eth/eventhandler/handlers.go
Adde verification mechanism to ensure the uniqueness of the operator's public key and ID
Handling OperatorAdded event we now check:
- there is no operator in storage with the same ID (otherwise throwing `ErrAlreadyRegisteredWithSameId`)
- there is no operator in storage with the same pubkey (otherwise throwing `ErrAlreadyRegisteredWithSamePubkey`)
> fix: (eventhandler) pubkey & id uniqueness check in OperatorAdded

- network/discovery/options.go
- networkconfig/holesky.go
- networkconfig/mainnet.go
- utils/boot_node/node.go
This PR:
- Disables `ProtocolID` for the testnet release ( in both node and bootnode)
- Sets the fork epoch of `holesky` testnet to 84600, // Oct-08-2024 12:00:00 PM UTC
- Sets `mainnet `fork epoch in the far future to avoid mistakes and to enable margin if we eventually change the date.
> alan testnet: disable protocol ID & set fork epochs

- message/validation/logger_fields.go
Setting the dutyID before we know the slot resulted in zeros in slot and epoch. this moves it forward so its set correctly.
> fix: msg validation dutyid set before slot

- network/commons/keys.go
- network/commons/keys_test.go
- protocol/genesis/qbft/instance/prepare.go
- protocol/v2/qbft/instance/prepare.go
We changed the way we read `Secp256k1PrivateKey` (#1734) to use `btcec`, but we skipped the "hack" that was instilled to make geth's discv5 be able to use our keys. this caused an issue where we would not do discovery, resulting in no peers and no duties.
Keep using new method but enforce the curve geth requires.
> fix: (bug) geth won't recognize ecdsa curve

- message/validation/common_checks.go
- message/validation/consensus_validation.go
- message/validation/partial_validation.go
- protocol/genesis/qbft/instance/prepare.go
- protocol/v2/qbft/instance/prepare.go
This PR fixes the committee role's duty limit by ensuring that unnecessary duty checks are skipped when the number of validators is high. It adjusts duty limit calculations and ensures proper checks for the sync committee based on validator count.
> fix: committee role duty limit

- message/validation/common_checks.go
- message/validation/validation_test.go
This PR fixes a bug where the first message of the last valid duty is accepted, but then the next messages would be rejected for "too many duties".
> fix: (validation) duty count check

- network/discovery/forking_dv5_listener.go
- network/discovery/forking_dv5_listener_test.go
We want to stop the pre-fork discovery only after a restart to keep it as simple as possible.
> fix: (alan) dont stop prefork discovery

- network/discovery/dv5_service.go
Since `RandomNodes()` func has internal way to wait for table to fill, it doesn't really need the sleep interval to not create a busy loop when its empty.
> fix (main): set discovery interval to 1ms

- network/discovery/dv5_service.go
Since `RandomNodes()` func has internal way to wait for table to fill, it doesn't really need the sleep interval to not create a busy loop when its empty.
> fix (stage): set discovery interval to 1ms

- cli/operator/node.go
- operator/node.go
We decided to not merge all custom domains to alan domain on fork, but to make them increase domain type value +1 and stay on a different domain. 
Genesis Domain Type -> Alan Domain Type
Genesis custom domain type -> Alan custom domain type (genesis +1)
> fix: change custom domain type to genesis custom domain type +1 on fork.

- message/validation/const.go
- message/validation/pubsub_validation.go
- network/topics/pubsub.go
Currently, the max message size supported by the protocol is `6286507` but default pub-sub max message size is 1 MiB according to https://github.com/libp2p/go-libp2p-pubsub/blob/f71345c1ec0ee4b30cd702bb605927f788ff9f36/pubsub.go#L495.
The PR changes the max pub-sub message size to MaxEncodedMsgSize (`6286507` as of now).
@MatheusFranco99 @GalRogozinski `go-libp2p-pubsub` discourages increasing the max size, should we consider reducing it?
> pubsub: set max msg size

- network/discovery/dv5_service.go
- network/discovery/options.go
Noticed the following log:
```
{
"level": "\u001b[35mDEBUG\u001b[0m",
"time": "2024-10-25T17:19:55.282860Z",
"name": "P2PNetwork",
"msg": "configuring discv5 discovery",
"selfPeer": "16Uiu2HAm5z6GYQaV4ddzic9zSugMFzgjtsUteCLWshkRXiKnodiy",
"subnets": "00000000000000000000000000000000",
"discOptsError": "json: unsupported type: basichost.AddrsFactory"
}
```
it seems `zap.Any` can't digest arbitrary structs and that results into this: `"discOptsError": "json: unsupported type: basichost.AddrsFactory"`, so in this PR I'm logging only most relevant options(hand-picked).
> fix: (discovery) logged configuration

- operator/validator/controller.go
- protocol/v2/ssv/validator/non_committee_validator.go
Adding a beacon vote cache seems to have broken saving roots in some way and caused a lot of "no roles found for quorum root" logs 
This PR is a hotfix that just reverts adding the cache and fixes those errors
If we decide to add the cache, we'll do it in another PR
> fix: (exporter) revert adding beacon vote cache

- ekm/signer_key_manager_test.go
> Concurrent slashing protection tests

- operator/slotticker/slotticker_test.go
- protocol/genesis/ssv/genesisqueue/queue_test.go
- protocol/v2/ssv/queue/queue_test.go
I'm running `make docker-unit-test` and it fails pretty reliably with errors like this one (attaching also [full log example](https://github.com/user-attachments/files/17257227/failed-tests.txt)):
```
github.com/ssvlabs/ssv/protocol/v2/ssv		coverage: 0.0% of statements
--- FAIL: TestPriorityQueue_Pop (0.22s)
queue_test.go:153:
Error Trace:	/go/src/github.com/ssvlabs/ssv/protocol/v2/ssv/queue/queue_test.go:153
Error:      	Max difference between 2024-10-04 08:32:38.253621092 +0000 UTC m=+0.420658418 and 2024-10-04 08:32:38.267124259 +0000 UTC m=+0.434161626 allowed is 5ms, but difference was -13.503208ms
Test:       	TestPriorityQueue_Pop
```
Looks like timeouts need to be increased (5ms->50ms change seems reasonable to me  because I'm encountering it on Mac M3 pro machine which is quite …
> tests: increase timeouts for flaky tests

- network/discovery/enode.go
Outputting `hostIP` when it's `nil` causes this log: `invalid host address given: <nil>`. `hostAddr` should be logged instead
> discovery: fix IP log when adding addresses

- network/peers/subnets.go
- network/peers/subnets_test.go
The logic is incorrect for `i != 0`, the peer is not removed.
This change is copied from https://github.com/ssvlabs/ssv/pull/1813 as it seems more important
> peers: fix subnets index removal logic

- message/validation/consensus_validation.go
- message/validation/validation_test.go
move ErrUnexpectedConsensusMessage ErrRoundTooHigh to be triggered as soon as possible to be able to replicate them in the attack sim
@MatheusFranco99 please adjust the knowledge base
> message validation: rearrange checks

- network/p2p/p2p_validation_test.go
I've been observing flaky test running `make docker-unit-test` (eg. https://github.com/ssvlabs/ssv/actions/runs/11482239405/job/31954803590, it also seems to be the Case 1 described in https://github.com/ssvlabs/ssv/issues/1578):
```
--- FAIL: TestP2pNetwork_MessageValidation (11.50s)
p2p_validation_test.go:279:
Error Trace:	/go/src/github.com/ssvlabs/ssv/network/p2p/p2p_validation_test.go:279
Error:      	Not equal:
expected: 3
actual  : 2
Test:       	TestP2pNetwork_MessageValidation
Messages:   	node 3
FAIL
coverage: 12.7% of statements
FAIL	github.com/ssvlabs/ssv/network/p2p	15.897s
```
This occasional failure seems to be due to the way `sync.Map` is being iterated with `Range` method (namely there is no way to get a consistent view for the whole map). In this PR I've simply changed …
> tests: p2p validation - use correct mutex to read roleBroadcasts changes

- eth/executionclient/execution_client.go
- eth/executionclient/execution_client_test.go
- eth/executionclient/options.go
This PR resolves potential memory leak (similar to what's described in https://github.com/ssvlabs/ssv/pull/1780), also simplifying the test affected.
> tests: executionclient fix & simplify

- Dockerfile
Closes https://github.com/ssvlabs/ssv/issues/1718
Pinned versions often get removed, so Docker fails to build an image until we update it
> Dockerfile: no version pinning

- registry/storage/shares.go
The approach taken here is to minimize the time spent with a locked `shares` map.
By separately locking the badger instance we allow access to the in-memory shares while the "heavy lifting" disk access is being executed.
> perf(registry/storage): don't lock in-memory shares storage for database ops 

- beacon/goclient/aggregator.go
- beacon/goclient/attest.go
- beacon/goclient/goclient.go
- beacon/goclient/observability.go
- beacon/goclient/proposer.go
- beacon/goclient/sync_committee.go
- beacon/goclient/sync_committee_contribution.go
**Metrics added**
- `ssv.cl.attestation_data_request.duration` (`ssv.beacon.role` attribute(global))
- `ssv.cl.sync.status` (`ssv.cl.addr`, `ssv.cl.sync.status` attributes)
- `ssv.cl.sync.distance` (`ssv.cl.addr` attribute) **(new!)**
**Metrics removed**
- `ssv_beacon_status`
- `ssv_beacon_data_request_duration_seconds` (`role` label)
**Questions and opinions**
- `ssv.cl.syncing` namespace name. Although, it is aligned with this [PR](https://github.com/ssvlabs/ssv/pull/1852). The alternative could be `ssv.cl.sync` (`ssv.cl.sync.status`).
- `ssv.beacon.role` attribute name. Alternatives: `ssv.consensus.role`, `ssv.validator.role`. What does sound more correct to you? Keep in mind that OTeL metric attributes also have a concept of _namespaces_, so in this case `ssv.consensus`, `ssv.beacon`, …
> feat(metrics): OTeL - instrument Consensus Client

- protocol/v2/ssv/validator/timer.go
The warning `no committee runner found for slot` is only encountered after we prune the runners after a round timed out.
This PR changes the log level for the message.
> chore: set log to debug level [main]

- message/validation/common_checks.go
- message/validation/consensus_validation.go
- message/validation/partial_validation.go
- message/validation/validation_test.go
- networkconfig/holesky-stage.go
- operator/duties/dutystore/duties.go
- operator/duties/proposer.go
- utils/testutils.go
close https://github.com/ssvlabs/ssv/issues/1827
Solution:
Don't ignore first slot proposal pre-consensus messages (randao) as long as the ProposerHandler has not fetched the duties.
The impact of this change from an attack perspective is minor, as the attacker must be part of the committee (i.e., possess a private key)
duplicate https://github.com/ssvlabs/ssv/pull/1886
> hotfix(MessageValidation): first slot proposals [main]

- network/discovery/dv5_service.go
- network/discovery/forking_dv5_listener.go
- network/discovery/forking_dv5_listener_test.go
- network/discovery/iterator_test.go
- network/discovery/options.go
- network/discovery/service_test.go
- network/discovery/shared_conn.go
- network/discovery/util_test.go
- network/records/entries.go
We noticed that Discovery isn't working as expected after #1820 , after some testing we realized there's some issue also present from previous versions but the dual discovery in alan works as a workaround. So this change basically brings back this part of the code (dual discovery) with some adjustment to the new domain type code.
> chore(discovery): re-enable post-fork discovery and NextDomainType

- operator/validator/controller.go
- operator/validator/observability.go
- protocol/v2/ssv/runner/observability.go
```
epoch 1
role: Proposer
nrOfSubmissions: 1
```
Should result in gauge record being set to 1. _Works_
On new epoch start should reset map to 0. _Works_
```
epoch 2
role: Proposer
nrOfSubmissions: 0
```
Should result in gauge record  being set to 0. _Dot not work_. Reason: `submission.epoch != 0` return `false`, because reset set epoch to 0.
Rename some of the validator statuses
> fix(metrics): set epoch when reset submissions gauge, refactor validator status names

- operator/duties/observability.go
- operator/duties/scheduler.go
`ssv.beacon.role` was not set correctly, hence there is an option of using `ssv.runner.role` instead. 
To keep `ssv.beacon.role` it would be required to iterate over all duties within Committee Duty object, which would add `O(n)` where `n` is a number of duties time complexity to the duty scheduling, which is a trade-off. I am incline towards switching to `ssv.runner.role` attribute
> fix(metrics):  ssv.duty.scheduler.executions - replace attribute

- network/commons/common.go
- network/commons/common_test.go
- operator/validator/controller.go
I observed high memory usage and a lot of allocations stemming from the `CommitteeSubnet` code used to calculate the subnets for which validators we should pull metadata for (Changed in #1787)
- Initialized a global `SubnetsCount` `big.Int` representation to reduce allocations.
- Created `SetCommitteeSubnet` which receives a `big.Int` instance and uses it instead of allocating new ints.
- Used the new function in all the metadata collection loop calls to CommitteeSubnet.
> refactor: optimize subnet calculations using big.Int for reduced memory usage

- beacon/goclient/validator.go
**Description:**
Durations of all outgoing HTTP requests to _Consensus Node_ are monitored via metrics. This particular endpoint was previously missing
> feat(metrics) - Beacon client 'Validators' endpoint request duration metric

- eth/eventsyncer/event_syncer.go
temporarily remove the check while a proper solution is implemented
> fix(eventsyncer): remove check for block below threshold in the sync history method

- eth/executionclient/execution_client.go
> feat(metrics) - EL status 'syncing' distance above threshold

- network/topics/container.go
**Problem**
Messages from `libp2p` were being validated successfully but were not reaching the message queue.
Upon enabling logs for the `libp2p pubsub` package, it was discovered that the following error was causing message drops:
```
Can't deliver message to subscription for topic ssv.v2....; subscriber too slow
```
This occurred because the default subscription buffer size was too small (32), resulting in messages being dropped when the buffer was full.
**Solution**
- Increased the subscription buffer size to `128` to handle bursts of incoming messages and reduce message drops.
- The value 128 was chosen based on:
- It provides 4x the default buffer size, which is sufficient for moderate workloads.
- it balances memory usage and burst tolerance without overcommitting resources.
After …
> fix(pubsub): increase subscription buffer size to prevent message drops

- operator/validator/controller.go
- protocol/v2/ssv/validator/non_committee_validator.go
Log line refers to a previously removed field causing a `panic`. Fixed by passing the missing value.
> fix(exporter): missing identifier value

- .github/dependabot.yml
- .github/workflows/spec-alignment.yml
Some of our pipelines started to fail, because of outdated GitHub Actions, hence I am adding this dependabot config so it can keep it up to date.
Also, I think we should add dependabot config for stuff like Docker, Go deps, etc. Not adding it now, since it will spam a lot of PRs, so probably we need to discuss that beforehand
**Update:**  
After this PR is merged into the **main** branch, Dependabot will create PRs on a weekly basis for updates to the GitHub Actions used in this repository. It’s unlikely to generate new PRs every week, as new releases for GitHub Actions are not frequent.
> chore(dependabot) - Dependabot config github actions

- operator/duties/sync_committee_test.go
Given unit test was sometimes failing with a message like:
`Error:      	"49.996792ms" is not greater than "50ms"`
The fix does not make the test entirely consistent, instead, it adds a 10% margin. This means the test will pass if the sync committee duty execution time is higher than `45ms` (previously `50ms`). (Slot duration is mocked to be [150ms](https://github.com/ssvlabs/ssv/blob/main/operator/duties/scheduler_test.go#L116) instead of the default 12 seconds).
**PS:** I am not sure what exactly this test verifies, but it seems the sync committee duty execution time should be **higher than 50ms**. I ran the test over 1000 times with this change, and there were no failures anymore.
> fix(flaky test) - fix inconsistent results in unit test

- network/p2p/config.go
Originally this issue was raised by Kraken team, namely they couldn't set `HostDNS` such that it would work - it would fail with:
```
2025-01-21T12:58:53.223889Z	FATAL	failed to setup network	{"error": "could not create p2p host: cannot specify multiple address factories", "errorVerbose": "cannot specify multiple address factories\ncould not create p2p host\ngithub.com/ssvlabs/ssv/network/p2p.(*p2pNetwork).SetupHost\n\t/go/src/github.com/ssvlabs/ssv/network/p2p/p2p_setup.go:136\ngithub.com/ssvlabs/ssv/network/p2p.(*p2pNetwork).Setup\n\t/go/src/github.com/ssvlabs/ssv/network/p2p/p2p_setup.go:67\ngithub.com/ssvlabs/ssv/cli/operator.init.func2\n\t/go/src/github.com/ssvlabs/ssv/cli/operator/node.go:445\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/comm …
```
> config: p2p, fix parsing HostDNS

- network/discovery/dv5_service.go
This repeats https://github.com/ssvlabs/ssv/pull/1818 which probably was lost during some rebase (I've accidentally noticed this error in logs on **stage** again).
> fix: (discovery) logged configuration (attempt 2)

- eth/executionclient/execution_client.go
Without the comment, it's not clear why we didn't choose `SubscribeFilterLogs`
> executionclient: add a comment about SubscribeNewHead choice

- ibft/storage/store.go
This metric was not migrated to OTeL because it was not used and was high cardinality metric. It should have been removed
> fix(metrics) - Drop unused prometheus metric

- eth/executionclient/defaults.go
- eth/executionclient/multi_client.go
> eth/executionclient: rate limit multi client Healthy call

- message/validation/common_checks.go
- message/validation/const.go
- protocol/v2/ssv/validator/non_committee_validator.go
I already fixed it in #1859, but we haven't merged it so we kept running with the leak.
> fix: (exporter) memory leak in partial sig container

- cli/operator/node.go
We added a separate metadata syncer component in #1712 , We copied over the logic for `FixedSubnets`, but we called p2p to get it, but since `p2p` we only setup later, the value was empty.
This PR parses the fixed subnets separately for the syncer, and sets it to all subnets for an Exporter.
>  fix(Exporter): set fixed subnets to all subnets if exporter is set #2025 

- beacon/goclient/goclient.go
The race condition was caught by the [test from the feature branch](https://github.com/ssvlabs/ssv/actions/runs/13518370221/job/37776658631?pr=2018#step:5:22). That particular test instantiates GoClient with multiple Beacon Servers. This issue occurs when there are two or more Beacon Servers used by the GoClient
> fix(GoClient) - fix race condition

- .github/workflows/e2e-test.yml
Currently, E2E tests are not functioning, leading to pipeline failures. This PR disables the pipeline triggers. Once the E2E tests are fixed, the triggers can be re-enabled.
> Disable e2e CI workflow triggers

- .github/dependabot.yml
By default, dependabot targets `default` branch which in our case is `main`.
Following our workflow, we want dependabot to target `stage` branch instead.
Configuration [description](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#target-branch-)
> chore(dependabot) - change dependabot target branch to 'Stage'

- utils/tasks/exec_timeout.go
- utils/tasks/exec_timeout_test.go
I observed this test failing, sketched a fix for it (alternatively we might want to remove this code completely instead because it's not really used anywhere at the moment)
```
--- FAIL: TestExecWithTimeout (0.02s)
--- FAIL: TestExecWithTimeout/Long_function (0.01s)
exec_timeout_test.go:58:
Error Trace:	/go/src/github.com/ssvlabs/ssv/utils/tasks/exec_timeout_test.go:58
Error:      	"2" is not greater than or equal to "3"
Test:       	TestExecWithTimeout/Long_function
2024-10-14T16:36:58.283178Z	DEBUG	logger is ready	{"level": "debug", "encoder": "capital", "format": "console", "file_options": null}
FAIL
coverage: 82.2% of statements
FAIL	github.com/ssvlabs/ssv/utils/tasks
```
> utils: fix flaky tests

- beacon/goclient/events_test.go
- beacon/goclient/goclient_test.go
- beacon/goclient/tests/shared.go
I've noticed there are couple of issues:
- `t *testing.T` is not meant to be used concurrently:
```go
// T is a type passed to Test functions to manage test state and support formatted test logs.
//
// A test ends when its Test function returns or calls any of the methods
// FailNow, Fatal, Fatalf, SkipNow, Skip, or Skipf. Those methods, as well as
// the Parallel method, must be called only from the goroutine running the
// Test function.
//
// The other reporting methods, such as the variations of Log and Error,
// may be called simultaneously from multiple goroutines.
type T struct {
```
- and there is also this error (see https://stackoverflow.com/questions/57828645/how-to-handle-superfluous-response-writeheader-call-in-order-to-return-500 for more details):
```
2025/02/27 10:15:16 …
```
> beacon-client: fix concurrency issues in tests

- eth/eventsyncer/event_syncer.go
- eth/eventsyncer/event_syncer_test.go
This PR doubles the stalenessThreshold to prevent crashing when there are too many missed blocks in the network (such as recently witnessed on Holesky).
> fix: double eventsyncer stalenessThreshold

- network/discovery/dv5_service.go
We've received complaints about discovery traffic from bootnode operators. This should reduce it by a bit.
> chore(discovery): double discovery interval

- cli/operator/node.go
- go.mod
- go.sum
- message/validation/const.go
- message/validation/pubsub_validation.go
- message/validation/validation.go
- message/validation/validation_test.go
- network/p2p/test_utils.go
- network/topics/controller_test.go
- network/topics/msg_validator_test.go
In this PR we use the new spec version which include new sizes for block SSZ encoding which accounts for new blob sizes and exec payloads in pectra. It also addresses a possible attack vector by not accepting big messages in validation before pectra fork epoch.
> fix: bump spec to v1.1.3 and add pectra block size check

- cli/bootnode/boot_node.go
- cli/config/config.go
- cli/operator/node.go
- eth/executionclient/config.go
- logging/global.go
- network/discovery/dv5_bootnode.go
- network/p2p/config.go
- operator/node.go
- operator/validator/controller.go
- protocol/v2/blockchain/beacon/client.go
- storage/basedb/storage.go
- utils/boot_node/node.go
> [!WARNING]
> Idk, but I think, it its possible to replace two envs: `HostAddress` and `HostDNS` with `Host`. They came from: `network/p2p/config.go`. It would be technically possible to combine them into a single Host variable, the system would need to detect whether the value is an IP address or a DNS name (`net.ParseIP()`). And it can be done in `configureAddrs` method. The question of backward compatibility remains? 
Configs:
- Added examples for complex configurations
- Added valid values in parentheses for enum-like options
- [filename](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_170) in posix terminology means something else, we should use the correct name, lumberjack.Logger uses the wrong naming, so in `LogFileOptions` I changed `FileName` to …
> refactor: standarize env variable descriptions 

- protocol/v2/ssv/runner/committee.go
We were logging `time.Since(measurements.consensusStart)` while when we called `EndConsensus` `consensusTime` was reset, meaning we printed `maxInt64` value of duration instead of real duration. This PR changes to use the `measurements.ConsensusTime()` function instead which inside uses the `consensusDuration` var which is set with `time.Since(measurements.consensusStart)` before it is reset.  Also using the function makes sure to adhere to any future changes internal to the `measurements` struct.
https://github.com/ssvlabs/ssv/blob/62bda6701775b8e4e870db662963fa8ae25903a0/protocol/v2/ssv/runner/measurements.go#L59-L66
**NOTE**: I think we could've just not reset the `consensusStart` instead, but this is something we do for some reason even with other fields in `measurements` so I decided …
> fix: (committee.go) log correct total consensus time

- network/p2p/p2p.go
`SubscribeRandoms` is used in cases where the operator still doesn't have any validators according to the contract but we still want it to participate in the p2p network. In this case it will find random subnets and connect their peers.
Changes in the way we subscribe to subnets have created a scenario that when `SubscribeRandoms` tried to check the `activeSubents` its still not initialized. This caused the node to panic on out of bounds index when running with no validators ( A very rare case, this is why we haven't noticed it.)
This change initializes active subnets with 0's on the initialization on the node.
> fix: (p2p) init random subnets to prevent crash on random subnets.

- Makefile
- beacon/goclient/attest.go
- beacon/goclient/attest_test.go
- beacon/goclient/committee_subscribe.go
- beacon/goclient/events.go
- beacon/goclient/events_test.go
- beacon/goclient/goclient.go
- beacon/goclient/proposer.go
- beacon/goclient/sync_committee.go
- protocol/v2/blockchain/beacon/client.go
This PR addresses several edge cases that may occur during the weighted attestation data flow, particularly those related to scoring.
- The singleflight lock on block root lookups was removed, allowing all clients to retrieve the slot by block root in parallel. This change increases the likelihood of successfully fetching the slot, which is critical for scoring. A vulnerability in the previous implementation was that if one client timed out, other clients might not get a chance to perform the same lookup due to the soft timeout being reached.
- Retry logic was introduced for fetching the slot by block root. This addition is important, as the Block event often arrives just a few milliseconds after the initial scoring attempt, which previously led to slot being not included in the score.
- …
> perf: weighted attestation data enhancements

- network/p2p/p2p.go
`SubscribeRandoms` is used in cases where the operator still doesn't have any validators according to the contract but we still want it to participate in the p2p network. In this case it will find random subnets and connect their peers.
Changes in the way we subscribe to subnets have created a scenario that when `SubscribeRandoms` tried to check the `activeSubents` its still not initialized. This caused the node to panic on out of bounds index when running with no validators ( A very rare case, this is why we haven't noticed it.)
This change initializes active subnets with 0's on the initialization on the node.
> hotfix: (p2p) init random subnets to prevent crash on random subnets. 

- operator/validator/controller.go
- protocol/v2/ssv/validator/startup.go
This hotfix ensures `startValidatorsForMetadata` returns the correct number of newly started validators.
- Previously, the return value from `startValidator` was not respected, leading to an inaccurate count.
- As a result, `indicesChange` could be incorrectly triggered after metadata updates.
- The count is now accurate, preventing unnecessary duty refreshes.
The full solution will be provided in [#2060](https://github.com/ssvlabs/ssv/pull/2060).
This hotfix is a minimal step toward resolving [#2037](https://github.com/ssvlabs/ssv/issues/2037) until the full fix is merged.
> hotfix: prevent false `indicesChange` trigger on metadata update

- Makefile
- operator/keys/rsa_benchmark_test.go
- operator/keys/rsa_linux.go
Revamp of https://github.com/ssvlabs/ssv/pull/1799 to add **go** vs **openssl** benchmarks
> benchmarks: go vs openssl rsa implementations

- beacon/goclient/attest_test.go
- beacon/goclient/events_test.go
- beacon/goclient/goclient.go
- beacon/goclient/goclient_test.go
- beacon/goclient/options.go
- cli/operator/node.go
- protocol/v2/blockchain/beacon/client.go
Part of PRs that will replace https://github.com/ssvlabs/ssv/pull/1308
> refactor(beacon/goclient): move beacon options from protocol/v2/blockchain/beacon

- cli/operator/node.go
- eth/ethtest/utils_test.go
- eth/eventhandler/event_handler.go
- eth/eventhandler/event_handler_test.go
- eth/eventsyncer/event_syncer_test.go
Removing it as it was replaced by `networkconfig.NetworkConfig`
> chore(eventhandler): remove unused beacon node attribute

- Dockerfile.multiarch
> [!IMPORTANT]  
> This PR should be merged before the next release.
> It solves: https://github.com/ssvlabs/ssv/issues/2182
```md
When building for ARM64 on an AMD64 host (or vice versa), the resulting binary had the host architecture rather than the target architecture.
1. **Added Target Architecture Development Libraries**
- Used `dpkg --add-architecture` to enable multi-arch support
- Installed `libc6-dev:<target-arch>` packages to provide proper static libraries
- Ensured availability of architecture-specific `libm.a` and `libmvec.a`
2. **Ensured Proper Cross-Compiler Selection**
- Maintained explicit compiler selection based on `TARGETARCH`
- Mapped each architecture to its specific cross-compiler:
- AMD64: `x86_64-linux-gnu-gcc`
- ARM64: `aarch64-linux-gnu-gcc`
- ARM: …
```
> fix(Dockerfile.multiarch): Cross-compilation wasn't producing correct architecture binaries

- network/commons/subnets.go
The SubnetsFromString function was returning an error for empty string instead of just returning zero subnets.
> fix: subnets count parsing empty string

- cli/operator/node.go
https://github.com/ssvlabs/ssv/pull/2151 seems to have broken remote signer initialization, causing a nil pointer dereference panic
> ssvsigner: fix panic on remote signer initialization

- eth/executionclient/execution_client.go
- eth/executionclient/mocks.go
- eth/executionclient/multi_client.go
- eth/executionclient/multi_client_test.go
Fix bug with increasing `fromBlock` when we shouldn't increase it. `streamLogsToChan` currently returns the last block it fetched even if it errored. The new logic returns the next block to process
> executionclient: fix log streaming logic

- go.mod
- go.sum
use https://github.com/attestantio/go-eth2-client/tree/fulu with a fix for https://github.com/attestantio/go-eth2-client/issues/230: https://github.com/ssvlabs/go-eth2-client/tree/fulu%2Bconsensus-block-value
> fix(go.mod): update go-eth2-client version to fix fetching config from teku 25.5.0

- operator/validator/controller.go
- protocol/v2/ssv/runner/proposer.go
- protocol/v2/ssv/testing/runner.go
This is useful to have a log line for, just in case we need to debug it (as per https://github.com/ssvlabs/ssv/pull/2262#discussion_r2127047455 suggestion).
> proposer-delay: log warn for capped value

- ssvsigner/cmd/purge-keys/purge-keys.go
> The main() function creates a logger with the zap.NewDevelopment() constructor. The docs at
https://pkg.go.dev/go.uber.org/zap#NewDevelopment state the following:
> 
> ```
> NewDevelopment builds a development Logger that writes DebugLevel and above logs to standard error in a human-friendly format.
> ```
> 
> That said, the logger will be run in debug mode, which will result in verbose message that may leak sensitive information.
> [SSV-18] ssvsigner: Insecure Logger Usage May Lead to Information Disclosure

- ssvsigner/server.go
> Implement a panic recovery mechanism within the deferred function in the `Handler` method’s returned
`fasthttp.RequestHandler`.
> [SSV-3] ssvsigner: Lack of Panic Recovery in Http Handler Wrapper Can Lead to Server Crash

- ssvsigner/cmd/internal/logger/logger.go
- ssvsigner/cmd/internal/validation/url.go
- ssvsigner/cmd/internal/validation/url_test.go
- ssvsigner/cmd/purge-keys/purge-keys.go
- ssvsigner/cmd/ssv-signer/ssv-signer.go
- ssvsigner/cmd/ssv-signer/ssv-signer_test.go
**Description**: The `Web3SignerEndpoint` configuration parameter, sourced from CLI arguments or environment variables, is
validated by `validateConfig` using `url.ParseRequestURI `. This validation is insufficient as `url.ParseRequestURI` allows
various URL schemes and does not restrict target hosts (e.g., `localhost` , internal IPs, potentially other schemes if not filtered by
the HTTP client). The validated endpoint is then used by `setupWeb3SignerClient` to instantiate a `web3signer.Web3Signer`
client, which makes HTTPS requests. An attacker who can control the `WEB3SIGNER_ENDPOINT` value could specify an endpoint
pointing to internal network services (e.g., `http://localhost:xxxx , http://internal-service.local/api `). This could
allow the attacker to scan internal networks, access …
> [SSV-20] ssvsigner: Server-Side Request Forgery via Web3signer_endpoint Configuration

- ssvsigner/client.go
- ssvsigner/client_test.go
- ssvsigner/server.go
- ssvsigner/server_test.go
> Implement a strict limit on the number of shares processed in a single `POST /v1/validators` request (e.g., 5–
10 shares). Clients adding many shares must batch their requests, reducing maximum processing time and CPU load per request.
> [SSV-5] ssvsigner: High CPU Usage and Potential DoS in the Add Validator Flow Due to Unbounded Share Processing

- operator/fee_recipient/controller_test.go
- operator/validator/controller_test.go
This PR aims to address the `TestHandleNonCommitteeMessages` flaky failure (see failing Github pipeline https://github.com/ssvlabs/ssv/actions/runs/15730946442/job/44331699107):
```
2025-06-18T11:03:47.556136Z	DEBUG	TestHandleNonCommitteeMessages	router message handler stopped
panic: time out!
goroutine 142 [running]:
github.com/ssvlabs/ssv/operator/validator.TestHandleNonCommitteeMessages.func2()
/home/runner/work/ssv/ssv/operator/validator/controller_test.go:307 +0x38
created by github.com/ssvlabs/ssv/operator/validator.TestHandleNonCommitteeMessages in goroutine 139
/home/runner/work/ssv/ssv/operator/validator/controller_test.go:305 +0xec7
FAIL	github.com/ssvlabs/ssv/operator/validator	6.608s
/usr/bin/ld: warning: bint64.o: missing .note.GNU-stack section implies executable stack …
```
> validator: attempt to fix flaky test TestHandleNonCommitteeMessages

- ssvsigner/ekm/remote_key_manager.go
> Reverse the order of operations in `AddShare()` so that local protection is initialized before the key is activated
remotely:
> 1. Call `km.BumpSlashingProtection(pubKey)` first.
> 2. Then call `km.signerClient.AddValidators(ctx, shareKeys)`.
> 
> This ensures that if `BumpSlashingProtection()` fails, the key is never added to the remote signer. If the remote call then fails, local protection is still correctly initialized, preventing any window where a slashable signing could occur.
> [SSV-10] ssvsigner: The Order of Operations in RemoteKeyManager.AddShare() May Lead to Ineffective Local Slashing Protection

- go.mod
- go.sum
- ssvsigner/client.go
- ssvsigner/client_test.go
- ssvsigner/ekm/mock.go
- ssvsigner/ekm/remote_key_manager.go
- ssvsigner/ekm/remote_key_manager_test.go
port of https://github.com/ssvlabs/ssv/pull/2246 to main
> ssvsigner: handle request error after remote signer processed keys [main]

- networkconfig/holesky-e2e.go
- networkconfig/holesky-stage.go
- networkconfig/holesky.go
- networkconfig/hoodi-stage.go
- networkconfig/hoodi.go
- networkconfig/local-testnet.go
- networkconfig/mainnet.go
- networkconfig/sepolia.go
- networkconfig/ssv.go
- networkconfig/test-network.go
- protocol/v2/ssv/testing/runner.go
- protocol/v2/ssv/validator/opts.go
This PR is a port of https://github.com/ssvlabs/ssv/pull/2307 onto **main** branch
> fasttrack: gas-limit: default to 36

- go.mod
- go.sum
- ssvsigner/cmd/internal/validation/url.go
- ssvsigner/cmd/internal/validation/url_test.go
- ssvsigner/cmd/ssv-signer/ssv-signer_test.go
- ssvsigner/go.mod
- ssvsigner/go.sum
> `WEB3SIGNER_ENDPOINT` is validated only with `url.ParseRequestURI`, which allows schemes such as `http://localhost` or `http://10.x.x.x`.  
> An attacker who controls this value could make the SSV node call internal services (network scanning / sensitive endpoints).  
> Impact is limited because the node ↔ signer channel already uses mTLS.
---
| Argument | Details |
| -------- | ------- |
| **1. Input isn’t untrusted** | Only the node **operator** sets `WEB3SIGNER_ENDPOINT`. SSRF defences target *untrusted user* input (see OWASP SSRF: <https://owasp.org/www-community/attacks/Server_Side_Request_Forgery>). |
| **2. Private subnet = safer** | Signing services are best kept on RFC 1918 ranges (<https://www.rfc-editor.org/rfc/rfc1918>). Forcing a **public** IP increases exposure. |
| **3. …
> UPDATE [SSV-20] ssvsigner: Server-Side Request Forgery via Web3signer_endpoint Configuration 

- cli/generate_operator_keys.go
- go.mod
- go.sum
- ssvsigner/keystore/file.go
- ssvsigner/keystore/file_test.go
https://github.com/ssvlabs/ssv/pull/2028 changed the format of the public key in the generated keystore from `pubKey` to `pubkey`. Reverting it back might break something, and also the `pubkey` spelling seems preferrable as it's used in the [ERC-2335](https://github.com/ethereum/ercs/blob/master/ERCS/erc-2335.md#json-schema). So, this PR adds a `--legacy-pubkey` flag that makes `generate-operator-keys` use the legacy format
> generate-operator-keys: support legacy "pubKey" field in keystore

- operator/duties/attester.go
- operator/duties/proposer.go
- operator/duties/sync_committee.go
This is a backport of https://github.com/ssvlabs/ssv/pull/2476 - but instead of being its full blown carbon-copy it's a minimal working solution to fix the issue for **version/optimization** branch (so it can go into the upcoming v2.3.5 release ASAP without much of extra testing required). 
These changes are "minimal" to keep the future resolving of merge conflicts as simple as possible (once we eventually merge branches like **main**->**stage**).
> backport: duties: clarify & fix typos & fix sync-committee subscription
